/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificationsIndexRouteImport } from './routes/verifications/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as OperatorsIndexRouteImport } from './routes/operators/index'
import { Route as NationalDashboardIndexRouteImport } from './routes/national-dashboard/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as ImpersonateIndexRouteImport } from './routes/impersonate/index'
import { Route as FeatureFlagsIndexRouteImport } from './routes/feature-flags/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ComplianceIndexRouteImport } from './routes/compliance/index'
import { Route as CommitteesIndexRouteImport } from './routes/committees/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as AssociationsIndexRouteImport } from './routes/associations/index'
import { Route as OrganizationsOrganizationIdRouteImport } from './routes/organizations/$organizationId'
import { Route as MembersPersonIdRouteImport } from './routes/members/$personId'
import { Route as AssociationsAssociationIdRouteImport } from './routes/associations/$associationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationsIndexRoute = VerificationsIndexRouteImport.update({
  id: '/verifications/',
  path: '/verifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsIndexRoute = OperatorsIndexRouteImport.update({
  id: '/operators/',
  path: '/operators/',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalDashboardIndexRoute = NationalDashboardIndexRouteImport.update({
  id: '/national-dashboard/',
  path: '/national-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonateIndexRoute = ImpersonateIndexRouteImport.update({
  id: '/impersonate/',
  path: '/impersonate/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFlagsIndexRoute = FeatureFlagsIndexRouteImport.update({
  id: '/feature-flags/',
  path: '/feature-flags/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/compliance/',
  path: '/compliance/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesIndexRoute = CommitteesIndexRouteImport.update({
  id: '/committees/',
  path: '/committees/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationsIndexRoute = AssociationsIndexRouteImport.update({
  id: '/associations/',
  path: '/associations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MembersPersonIdRoute = MembersPersonIdRouteImport.update({
  id: '/members/$personId',
  path: '/members/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationsAssociationIdRoute =
  AssociationsAssociationIdRouteImport.update({
    id: '/associations/$associationId',
    path: '/associations/$associationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/associations/$associationId': typeof AssociationsAssociationIdRoute
  '/members/$personId': typeof MembersPersonIdRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/associations/': typeof AssociationsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/committees/': typeof CommitteesIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/events/': typeof EventsIndexRoute
  '/feature-flags/': typeof FeatureFlagsIndexRoute
  '/impersonate/': typeof ImpersonateIndexRoute
  '/members/': typeof MembersIndexRoute
  '/national-dashboard/': typeof NationalDashboardIndexRoute
  '/operators/': typeof OperatorsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/verifications/': typeof VerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/associations/$associationId': typeof AssociationsAssociationIdRoute
  '/members/$personId': typeof MembersPersonIdRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/associations': typeof AssociationsIndexRoute
  '/audit': typeof AuditIndexRoute
  '/committees': typeof CommitteesIndexRoute
  '/compliance': typeof ComplianceIndexRoute
  '/events': typeof EventsIndexRoute
  '/feature-flags': typeof FeatureFlagsIndexRoute
  '/impersonate': typeof ImpersonateIndexRoute
  '/members': typeof MembersIndexRoute
  '/national-dashboard': typeof NationalDashboardIndexRoute
  '/operators': typeof OperatorsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/training': typeof TrainingIndexRoute
  '/verifications': typeof VerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/associations/$associationId': typeof AssociationsAssociationIdRoute
  '/members/$personId': typeof MembersPersonIdRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/associations/': typeof AssociationsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/committees/': typeof CommitteesIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/events/': typeof EventsIndexRoute
  '/feature-flags/': typeof FeatureFlagsIndexRoute
  '/impersonate/': typeof ImpersonateIndexRoute
  '/members/': typeof MembersIndexRoute
  '/national-dashboard/': typeof NationalDashboardIndexRoute
  '/operators/': typeof OperatorsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/verifications/': typeof VerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/associations/$associationId'
    | '/members/$personId'
    | '/organizations/$organizationId'
    | '/associations/'
    | '/audit/'
    | '/committees/'
    | '/compliance/'
    | '/events/'
    | '/feature-flags/'
    | '/impersonate/'
    | '/members/'
    | '/national-dashboard/'
    | '/operators/'
    | '/organizations/'
    | '/training/'
    | '/verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/associations/$associationId'
    | '/members/$personId'
    | '/organizations/$organizationId'
    | '/associations'
    | '/audit'
    | '/committees'
    | '/compliance'
    | '/events'
    | '/feature-flags'
    | '/impersonate'
    | '/members'
    | '/national-dashboard'
    | '/operators'
    | '/organizations'
    | '/training'
    | '/verifications'
  id:
    | '__root__'
    | '/'
    | '/associations/$associationId'
    | '/members/$personId'
    | '/organizations/$organizationId'
    | '/associations/'
    | '/audit/'
    | '/committees/'
    | '/compliance/'
    | '/events/'
    | '/feature-flags/'
    | '/impersonate/'
    | '/members/'
    | '/national-dashboard/'
    | '/operators/'
    | '/organizations/'
    | '/training/'
    | '/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssociationsAssociationIdRoute: typeof AssociationsAssociationIdRoute
  MembersPersonIdRoute: typeof MembersPersonIdRoute
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRoute
  AssociationsIndexRoute: typeof AssociationsIndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  CommitteesIndexRoute: typeof CommitteesIndexRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FeatureFlagsIndexRoute: typeof FeatureFlagsIndexRoute
  ImpersonateIndexRoute: typeof ImpersonateIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  NationalDashboardIndexRoute: typeof NationalDashboardIndexRoute
  OperatorsIndexRoute: typeof OperatorsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  VerificationsIndexRoute: typeof VerificationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifications/': {
      id: '/verifications/'
      path: '/verifications'
      fullPath: '/verifications/'
      preLoaderRoute: typeof VerificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/': {
      id: '/operators/'
      path: '/operators'
      fullPath: '/operators/'
      preLoaderRoute: typeof OperatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national-dashboard/': {
      id: '/national-dashboard/'
      path: '/national-dashboard'
      fullPath: '/national-dashboard/'
      preLoaderRoute: typeof NationalDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonate/': {
      id: '/impersonate/'
      path: '/impersonate'
      fullPath: '/impersonate/'
      preLoaderRoute: typeof ImpersonateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-flags/': {
      id: '/feature-flags/'
      path: '/feature-flags'
      fullPath: '/feature-flags/'
      preLoaderRoute: typeof FeatureFlagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees/': {
      id: '/committees/'
      path: '/committees'
      fullPath: '/committees/'
      preLoaderRoute: typeof CommitteesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associations/': {
      id: '/associations/'
      path: '/associations'
      fullPath: '/associations/'
      preLoaderRoute: typeof AssociationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$personId': {
      id: '/members/$personId'
      path: '/members/$personId'
      fullPath: '/members/$personId'
      preLoaderRoute: typeof MembersPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associations/$associationId': {
      id: '/associations/$associationId'
      path: '/associations/$associationId'
      fullPath: '/associations/$associationId'
      preLoaderRoute: typeof AssociationsAssociationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssociationsAssociationIdRoute: AssociationsAssociationIdRoute,
  MembersPersonIdRoute: MembersPersonIdRoute,
  OrganizationsOrganizationIdRoute: OrganizationsOrganizationIdRoute,
  AssociationsIndexRoute: AssociationsIndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  CommitteesIndexRoute: CommitteesIndexRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  FeatureFlagsIndexRoute: FeatureFlagsIndexRoute,
  ImpersonateIndexRoute: ImpersonateIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  NationalDashboardIndexRoute: NationalDashboardIndexRoute,
  OperatorsIndexRoute: OperatorsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  VerificationsIndexRoute: VerificationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
