#!/usr/bin/env bun
/**
 * Parse the Playwright JSON reporter output from a `--repeat-each=N`
 * nightly run and emit docs/audits/E2E_FLAKE_LOG.md sorted by flake rate.
 *
 * Flake rate = failures / total_runs, computed per `(file, test_title)` pair.
 * A test is flaky when 0 < failures < total_runs. Tests that always pass
 * or always fail are not flaky — they're stable green or stable red and
 * belong in their own worklists.
 *
 * Usage:
 *   bun scripts/audit/flake-log.ts <path-to-playwright-json>
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname, relative } from 'node:path'

const input = process.argv[2]
if (!input) {
  console.error('usage: flake-log.ts <playwright-json>')
  process.exit(1)
}
if (!existsSync(input)) {
  console.error(`input file does not exist: ${input}`)
  process.exit(1)
}

interface PwTestResult {
  status: 'passed' | 'failed' | 'timedOut' | 'skipped' | 'interrupted'
}
interface PwTest {
  title: string
  results: PwTestResult[]
}
interface PwSpec {
  title: string
  file: string
  tests: PwTest[]
}
interface PwSuite {
  title?: string
  file?: string
  specs?: PwSpec[]
  suites?: PwSuite[]
}
interface PwReport {
  suites: PwSuite[]
}

function walkSpecs(suite: PwSuite, fileFallback: string, out: PwSpec[]): void {
  for (const spec of suite.specs ?? []) out.push(spec)
  for (const child of suite.suites ?? []) walkSpecs(child, suite.file ?? fileFallback, out)
}

const report = JSON.parse(readFileSync(input, 'utf8')) as PwReport
const specs: PwSpec[] = []
for (const suite of report.suites ?? []) walkSpecs(suite, suite.file ?? '<unknown>', specs)

interface Row {
  file: string
  title: string
  total: number
  passed: number
  failed: number
  rate: number
}

const rows: Row[] = []
for (const spec of specs) {
  for (const t of spec.tests ?? []) {
    const total = t.results.length
    const passed = t.results.filter((r) => r.status === 'passed').length
    const failed = t.results.filter((r) => r.status === 'failed' || r.status === 'timedOut').length
    if (total === 0) continue
    rows.push({
      file: spec.file ?? '<unknown>',
      title: t.title ?? spec.title,
      total,
      passed,
      failed,
      rate: failed / total,
    })
  }
}

const flaky = rows.filter((r) => r.passed > 0 && r.failed > 0).sort((a, b) => b.rate - a.rate)
const stableRed = rows.filter((r) => r.passed === 0 && r.failed > 0)
const stableGreen = rows.filter((r) => r.failed === 0).length

const repoRoot = join(import.meta.dir, '..', '..')
const outPath = join(repoRoot, 'docs/audits/E2E_FLAKE_LOG.md')
mkdirSync(dirname(outPath), { recursive: true })

const md: string[] = []
md.push('# E2E_FLAKE_LOG.md')
md.push('')
md.push(`Generated by \`scripts/audit/flake-log.ts\` on ${new Date().toISOString()}.`)
md.push('')
md.push('Tests are run N times by the nightly `e2e-flake-tracking` workflow. A test')
md.push('is flaky when it passes some runs and fails others under the same DB seed')
md.push('and code SHA.')
md.push('')
md.push(`## Summary`)
md.push('')
md.push(`- Total test instances scored: ${rows.length}`)
md.push(`- Stable green (all runs passed): ${stableGreen}`)
md.push(`- Stable red (all runs failed): ${stableRed.length}`)
md.push(`- **Flaky (mixed)**: ${flaky.length}`)
md.push('')
md.push('## Flaky tests — sorted by flake rate')
md.push('')
md.push('| Spec | Test | passed / total | flake rate |')
md.push('|---|---|---|---|')
for (const r of flaky) {
  const relFile = r.file.startsWith('/') ? relative(repoRoot, r.file) : r.file
  md.push(`| \`${relFile}\` | ${r.title} | ${r.passed} / ${r.total} | ${(r.rate * 100).toFixed(0)}% |`)
}
md.push('')
md.push('## Stable red — always fail (real bugs, not flakes)')
md.push('')
md.push('| Spec | Test |')
md.push('|---|---|')
for (const r of stableRed) {
  const relFile = r.file.startsWith('/') ? relative(repoRoot, r.file) : r.file
  md.push(`| \`${relFile}\` | ${r.title} |`)
}

writeFileSync(outPath, md.join('\n'))
console.log(`Wrote ${relative(repoRoot, outPath)}`)
console.log(`  stable green: ${stableGreen}`)
console.log(`  flaky: ${flaky.length}`)
console.log(`  stable red: ${stableRed.length}`)

// Exit non-zero if any spec exceeded 25% flake rate over a 3-run nightly —
// signals a regression worth waking someone up over.
const highFlake = flaky.filter((r) => r.rate >= 0.25)
if (highFlake.length > 0) {
  console.error(`\n${highFlake.length} test(s) above 25% flake rate — root-cause needed`)
  process.exit(1)
}
