#!/usr/bin/env bun
/**
 * Suggest `// WF-NNN` tags for Playwright specs by fuzzy-matching spec
 * titles to WORKFLOW_MAP.md flow descriptions. Suggestion-only — writes
 * docs/audits/WF_TAG_SUGGESTIONS.md, never edits specs.
 *
 * Motivation:
 *   Matrix B of coverage-matrix.ts (flow → spec) currently reports
 *   0/127 covered because specs don't annotate which WF they exercise.
 *   Tagging is one line per spec; the bottleneck is identifying which
 *   WF a spec covers. This script narrows the search.
 *
 * Scoring: token-overlap between spec describe/test titles + path keywords
 * vs WF description. Threshold-gated; ties listed for human disambiguation.
 *
 * Usage:
 *   bun scripts/audit/suggest-wf-tags.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { Glob } from 'bun'
import { join, relative } from 'node:path'

const repoRoot = join(import.meta.dir, '..', '..')

interface Flow {
  id: string         // WF-001
  module: string     // M01
  type: string
  description: string
  tokens: Set<string>
}

const STOPWORDS = new Set([
  'a', 'an', 'and', 'the', 'or', 'of', 'for', 'to', 'in', 'on', 'with', 'by',
  'is', 'are', 'be', 'been', 'has', 'have', 'this', 'that', 'these', 'those',
  'i', 'me', 'my', 'we', 'our', 'they', 'their', 'it', 'its', 'as', 'at',
  'from', 'into', 'over', 'page', 'shows', 'show', 'see', 'sees', 'view',
  'test', 'tests', 'spec', 'check', 'verify', 'render', 'renders', 'loads',
])

function tokenize(s: string): Set<string> {
  return new Set(
    s
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, ' ')
      .split(/\s+/)
      .filter((w) => w.length >= 3 && !STOPWORDS.has(w)),
  )
}

function jaccard(a: Set<string>, b: Set<string>): number {
  if (a.size === 0 || b.size === 0) return 0
  let inter = 0
  for (const t of a) if (b.has(t)) inter++
  const union = a.size + b.size - inter
  return inter / union
}

function parseFlows(): Flow[] {
  const path = join(repoRoot, 'docs/product/WORKFLOW_MAP.md')
  const md = readFileSync(path, 'utf8')
  const flows: Flow[] = []
  const re = /^\|\s*(WF-\d+)\s*\|\s*(M\d+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|/gm
  let m
  while ((m = re.exec(md)) !== null) {
    flows.push({ id: m[1]!, module: m[2]!, type: m[3]!.trim(), description: m[4]!.trim(), tokens: tokenize(m[4]!.trim()) })
  }
  return flows
}

async function scanSpecs(): Promise<{ rel: string; tokens: Set<string> }[]> {
  const out: { rel: string; tokens: Set<string> }[] = []
  const glob = new Glob('apps/memberry/tests/e2e/**/*.spec.ts')
  for await (const rel of glob.scan({ cwd: repoRoot })) {
    if (rel.includes('/stubs/')) continue
    const body = readFileSync(join(repoRoot, rel), 'utf8')

    // Skip specs already tagged
    if (/\/\/\s*WF-\d+/.test(body)) continue

    const titles = [
      ...(body.match(/test\.describe\s*\(\s*['"`]([^'"`]+)/g) ?? []).map((s) => s.replace(/.*['"`]/, '')),
      ...(body.match(/\btest\s*\(\s*['"`]([^'"`]+)/g) ?? []).map((s) => s.replace(/.*['"`]/, '')),
    ].join(' ')

    const pathKw = rel
      .replace(/apps\/memberry\/tests\/e2e\//, '')
      .replace(/\.spec\.ts$/, '')
      .replace(/[\/_-]/g, ' ')

    const tokens = tokenize(`${pathKw} ${titles}`)
    if (tokens.size > 0) out.push({ rel, tokens })
  }
  return out
}

const flows = parseFlows()
const specs = await scanSpecs()

interface Suggestion {
  rel: string
  matches: { flow: Flow; score: number }[]
}

const THRESHOLD = 0.15
const MIN_TOKENS_MATCH = 2

const suggestions: Suggestion[] = []
for (const spec of specs) {
  const scored = flows
    .map((flow) => {
      // count intersection so we can require at least N matched tokens.
      let inter = 0
      for (const t of flow.tokens) if (spec.tokens.has(t)) inter++
      const score = jaccard(spec.tokens, flow.tokens)
      return { flow, score, inter }
    })
    .filter((s) => s.score >= THRESHOLD && s.inter >= MIN_TOKENS_MATCH)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3)
  if (scored.length > 0) suggestions.push({ rel: spec.rel, matches: scored })
}

mkdirSync(join(repoRoot, 'docs/audits'), { recursive: true })
const outPath = join(repoRoot, 'docs/audits/WF_TAG_SUGGESTIONS.md')

const lines: string[] = []
lines.push('# WF_TAG_SUGGESTIONS.md — Suggested WF-id tags per spec')
lines.push('')
lines.push(`Generated by \`scripts/audit/suggest-wf-tags.ts\` on ${new Date().toISOString()}.`)
lines.push('')
lines.push(`Scanned ${specs.length} spec files against ${flows.length} flow definitions in \`docs/product/WORKFLOW_MAP.md\`.`)
lines.push(`Match threshold: Jaccard ≥ ${THRESHOLD}, minimum ${MIN_TOKENS_MATCH} token overlap.`)
lines.push('')
lines.push(`**${suggestions.length} specs have at least one candidate WF tag.** Apply with: prepend \`// WF-NNN — <description>\` to the spec's top.`)
lines.push('')
lines.push('## Suggestions (sorted by spec path)')
lines.push('')
for (const s of suggestions.sort((a, b) => a.rel.localeCompare(b.rel))) {
  lines.push(`### \`${s.rel}\``)
  lines.push('')
  for (const m of s.matches) {
    lines.push(`- \`${m.flow.id}\` (${m.flow.module}, score ${m.score.toFixed(2)}): ${m.flow.description}`)
  }
  lines.push('')
}

writeFileSync(outPath, lines.join('\n'))
console.log(`Wrote ${relative(repoRoot, outPath)}`)
console.log(`  ${specs.length} specs scanned`)
console.log(`  ${flows.length} flows considered`)
console.log(`  ${suggestions.length} specs have candidate WF tags`)
const top = suggestions.filter((s) => s.matches[0]!.score >= 0.4).length
console.log(`  ${top} specs have a strong match (score ≥ 0.40)`)
