/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MySettingsRouteImport } from './routes/my/settings'
import { Route as MyProfileRouteImport } from './routes/my/profile'
import { Route as MyPaymentsRouteImport } from './routes/my/payments'
import { Route as MyOrganizationsRouteImport } from './routes/my/organizations'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as OrgOrgIdMembersRouteImport } from './routes/org/$orgId/members'
import { Route as OrgOrgIdOfficerRosterRouteImport } from './routes/org/$orgId/officer/roster'
import { Route as OrgOrgIdOfficerPaymentsRouteImport } from './routes/org/$orgId/officer/payments'
import { Route as OrgOrgIdOfficerApplicationsRouteImport } from './routes/org/$orgId/officer/applications'
import { Route as OrgOrgIdOfficerSettingsDuesRouteImport } from './routes/org/$orgId/officer/settings/dues'
import { Route as OrgOrgIdOfficerSettingsChaptersRouteImport } from './routes/org/$orgId/officer/settings/chapters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySettingsRoute = MySettingsRouteImport.update({
  id: '/my/settings',
  path: '/my/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my/profile',
  path: '/my/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPaymentsRoute = MyPaymentsRouteImport.update({
  id: '/my/payments',
  path: '/my/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrganizationsRoute = MyOrganizationsRouteImport.update({
  id: '/my/organizations',
  path: '/my/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdMembersRoute = OrgOrgIdMembersRouteImport.update({
  id: '/org/$orgId/members',
  path: '/org/$orgId/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdOfficerRosterRoute = OrgOrgIdOfficerRosterRouteImport.update({
  id: '/org/$orgId/officer/roster',
  path: '/org/$orgId/officer/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdOfficerPaymentsRoute = OrgOrgIdOfficerPaymentsRouteImport.update({
  id: '/org/$orgId/officer/payments',
  path: '/org/$orgId/officer/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdOfficerApplicationsRoute =
  OrgOrgIdOfficerApplicationsRouteImport.update({
    id: '/org/$orgId/officer/applications',
    path: '/org/$orgId/officer/applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdOfficerSettingsDuesRoute =
  OrgOrgIdOfficerSettingsDuesRouteImport.update({
    id: '/org/$orgId/officer/settings/dues',
    path: '/org/$orgId/officer/settings/dues',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdOfficerSettingsChaptersRoute =
  OrgOrgIdOfficerSettingsChaptersRouteImport.update({
    id: '/org/$orgId/officer/settings/chapters',
    path: '/org/$orgId/officer/settings/chapters',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/my/organizations': typeof MyOrganizationsRoute
  '/my/payments': typeof MyPaymentsRoute
  '/my/profile': typeof MyProfileRoute
  '/my/settings': typeof MySettingsRoute
  '/org/$orgId/members': typeof OrgOrgIdMembersRoute
  '/org/$orgId/officer/applications': typeof OrgOrgIdOfficerApplicationsRoute
  '/org/$orgId/officer/payments': typeof OrgOrgIdOfficerPaymentsRoute
  '/org/$orgId/officer/roster': typeof OrgOrgIdOfficerRosterRoute
  '/org/$orgId/officer/settings/chapters': typeof OrgOrgIdOfficerSettingsChaptersRoute
  '/org/$orgId/officer/settings/dues': typeof OrgOrgIdOfficerSettingsDuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/my/organizations': typeof MyOrganizationsRoute
  '/my/payments': typeof MyPaymentsRoute
  '/my/profile': typeof MyProfileRoute
  '/my/settings': typeof MySettingsRoute
  '/org/$orgId/members': typeof OrgOrgIdMembersRoute
  '/org/$orgId/officer/applications': typeof OrgOrgIdOfficerApplicationsRoute
  '/org/$orgId/officer/payments': typeof OrgOrgIdOfficerPaymentsRoute
  '/org/$orgId/officer/roster': typeof OrgOrgIdOfficerRosterRoute
  '/org/$orgId/officer/settings/chapters': typeof OrgOrgIdOfficerSettingsChaptersRoute
  '/org/$orgId/officer/settings/dues': typeof OrgOrgIdOfficerSettingsDuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/my/organizations': typeof MyOrganizationsRoute
  '/my/payments': typeof MyPaymentsRoute
  '/my/profile': typeof MyProfileRoute
  '/my/settings': typeof MySettingsRoute
  '/org/$orgId/members': typeof OrgOrgIdMembersRoute
  '/org/$orgId/officer/applications': typeof OrgOrgIdOfficerApplicationsRoute
  '/org/$orgId/officer/payments': typeof OrgOrgIdOfficerPaymentsRoute
  '/org/$orgId/officer/roster': typeof OrgOrgIdOfficerRosterRoute
  '/org/$orgId/officer/settings/chapters': typeof OrgOrgIdOfficerSettingsChaptersRoute
  '/org/$orgId/officer/settings/dues': typeof OrgOrgIdOfficerSettingsDuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite/$token'
    | '/my/organizations'
    | '/my/payments'
    | '/my/profile'
    | '/my/settings'
    | '/org/$orgId/members'
    | '/org/$orgId/officer/applications'
    | '/org/$orgId/officer/payments'
    | '/org/$orgId/officer/roster'
    | '/org/$orgId/officer/settings/chapters'
    | '/org/$orgId/officer/settings/dues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$token'
    | '/my/organizations'
    | '/my/payments'
    | '/my/profile'
    | '/my/settings'
    | '/org/$orgId/members'
    | '/org/$orgId/officer/applications'
    | '/org/$orgId/officer/payments'
    | '/org/$orgId/officer/roster'
    | '/org/$orgId/officer/settings/chapters'
    | '/org/$orgId/officer/settings/dues'
  id:
    | '__root__'
    | '/'
    | '/invite/$token'
    | '/my/organizations'
    | '/my/payments'
    | '/my/profile'
    | '/my/settings'
    | '/org/$orgId/members'
    | '/org/$orgId/officer/applications'
    | '/org/$orgId/officer/payments'
    | '/org/$orgId/officer/roster'
    | '/org/$orgId/officer/settings/chapters'
    | '/org/$orgId/officer/settings/dues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MyOrganizationsRoute: typeof MyOrganizationsRoute
  MyPaymentsRoute: typeof MyPaymentsRoute
  MyProfileRoute: typeof MyProfileRoute
  MySettingsRoute: typeof MySettingsRoute
  OrgOrgIdMembersRoute: typeof OrgOrgIdMembersRoute
  OrgOrgIdOfficerApplicationsRoute: typeof OrgOrgIdOfficerApplicationsRoute
  OrgOrgIdOfficerPaymentsRoute: typeof OrgOrgIdOfficerPaymentsRoute
  OrgOrgIdOfficerRosterRoute: typeof OrgOrgIdOfficerRosterRoute
  OrgOrgIdOfficerSettingsChaptersRoute: typeof OrgOrgIdOfficerSettingsChaptersRoute
  OrgOrgIdOfficerSettingsDuesRoute: typeof OrgOrgIdOfficerSettingsDuesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/settings': {
      id: '/my/settings'
      path: '/my/settings'
      fullPath: '/my/settings'
      preLoaderRoute: typeof MySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/profile': {
      id: '/my/profile'
      path: '/my/profile'
      fullPath: '/my/profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/payments': {
      id: '/my/payments'
      path: '/my/payments'
      fullPath: '/my/payments'
      preLoaderRoute: typeof MyPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/organizations': {
      id: '/my/organizations'
      path: '/my/organizations'
      fullPath: '/my/organizations'
      preLoaderRoute: typeof MyOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/members': {
      id: '/org/$orgId/members'
      path: '/org/$orgId/members'
      fullPath: '/org/$orgId/members'
      preLoaderRoute: typeof OrgOrgIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/officer/roster': {
      id: '/org/$orgId/officer/roster'
      path: '/org/$orgId/officer/roster'
      fullPath: '/org/$orgId/officer/roster'
      preLoaderRoute: typeof OrgOrgIdOfficerRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/officer/payments': {
      id: '/org/$orgId/officer/payments'
      path: '/org/$orgId/officer/payments'
      fullPath: '/org/$orgId/officer/payments'
      preLoaderRoute: typeof OrgOrgIdOfficerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/officer/applications': {
      id: '/org/$orgId/officer/applications'
      path: '/org/$orgId/officer/applications'
      fullPath: '/org/$orgId/officer/applications'
      preLoaderRoute: typeof OrgOrgIdOfficerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/officer/settings/dues': {
      id: '/org/$orgId/officer/settings/dues'
      path: '/org/$orgId/officer/settings/dues'
      fullPath: '/org/$orgId/officer/settings/dues'
      preLoaderRoute: typeof OrgOrgIdOfficerSettingsDuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/officer/settings/chapters': {
      id: '/org/$orgId/officer/settings/chapters'
      path: '/org/$orgId/officer/settings/chapters'
      fullPath: '/org/$orgId/officer/settings/chapters'
      preLoaderRoute: typeof OrgOrgIdOfficerSettingsChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteTokenRoute: InviteTokenRoute,
  MyOrganizationsRoute: MyOrganizationsRoute,
  MyPaymentsRoute: MyPaymentsRoute,
  MyProfileRoute: MyProfileRoute,
  MySettingsRoute: MySettingsRoute,
  OrgOrgIdMembersRoute: OrgOrgIdMembersRoute,
  OrgOrgIdOfficerApplicationsRoute: OrgOrgIdOfficerApplicationsRoute,
  OrgOrgIdOfficerPaymentsRoute: OrgOrgIdOfficerPaymentsRoute,
  OrgOrgIdOfficerRosterRoute: OrgOrgIdOfficerRosterRoute,
  OrgOrgIdOfficerSettingsChaptersRoute: OrgOrgIdOfficerSettingsChaptersRoute,
  OrgOrgIdOfficerSettingsDuesRoute: OrgOrgIdOfficerSettingsDuesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
