/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyTokenRouteImport } from './routes/verify/$token'
import { Route as PayTokenRouteImport } from './routes/pay/$token'
import { Route as OrgSlugRouteImport } from './routes/org/$slug'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMyTrainingRouteImport } from './routes/_authenticated/my/training'
import { Route as AuthenticatedMySettingsRouteImport } from './routes/_authenticated/my/settings'
import { Route as AuthenticatedMyProfileRouteImport } from './routes/_authenticated/my/profile'
import { Route as AuthenticatedMyPaymentsRouteImport } from './routes/_authenticated/my/payments'
import { Route as AuthenticatedMyOrganizationsRouteImport } from './routes/_authenticated/my/organizations'
import { Route as AuthenticatedMyNotificationsRouteImport } from './routes/_authenticated/my/notifications'
import { Route as AuthenticatedMyIdCardRouteImport } from './routes/_authenticated/my/id-card'
import { Route as AuthenticatedMyEventsRouteImport } from './routes/_authenticated/my/events'
import { Route as AuthenticatedMyDataExportRouteImport } from './routes/_authenticated/my/data-export'
import { Route as AuthenticatedOrgOrgSlugRouteRouteImport } from './routes/_authenticated/org/$orgSlug/route'
import { Route as AuthenticatedMyCreditsIndexRouteImport } from './routes/_authenticated/my/credits/index'
import { Route as AuthenticatedMyCertificatesIndexRouteImport } from './routes/_authenticated/my/certificates/index'
import { Route as AuthenticatedOrgOrgSlugOfficerRouteImport } from './routes/_authenticated/org/$orgSlug/officer'
import { Route as AuthenticatedOrgOrgSlugMembersRouteImport } from './routes/_authenticated/org/$orgSlug/members'
import { Route as AuthenticatedOrgOrgSlugHomeRouteImport } from './routes/_authenticated/org/$orgSlug/home'
import { Route as AuthenticatedOrgOrgSlugDuesRouteImport } from './routes/_authenticated/org/$orgSlug/dues'
import { Route as AuthenticatedMyCreditsLogRouteImport } from './routes/_authenticated/my/credits/log'
import { Route as AuthenticatedMyCertificatesCertificateIdRouteImport } from './routes/_authenticated/my/certificates/$certificateId'
import { Route as AuthenticatedOrgOrgSlugTrainingIndexRouteImport } from './routes/_authenticated/org/$orgSlug/training/index'
import { Route as AuthenticatedOrgOrgSlugEventsIndexRouteImport } from './routes/_authenticated/org/$orgSlug/events/index'
import { Route as AuthenticatedOrgOrgSlugElectionsIndexRouteImport } from './routes/_authenticated/org/$orgSlug/elections/index'
import { Route as AuthenticatedOrgOrgSlugTrainingTrainingIdRouteImport } from './routes/_authenticated/org/$orgSlug/training/$trainingId'
import { Route as AuthenticatedOrgOrgSlugOfficerRosterRouteImport } from './routes/_authenticated/org/$orgSlug/officer/roster'
import { Route as AuthenticatedOrgOrgSlugOfficerPaymentsRouteImport } from './routes/_authenticated/org/$orgSlug/officer/payments'
import { Route as AuthenticatedOrgOrgSlugOfficerOfficersRouteImport } from './routes/_authenticated/org/$orgSlug/officer/officers'
import { Route as AuthenticatedOrgOrgSlugOfficerDashboardRouteImport } from './routes/_authenticated/org/$orgSlug/officer/dashboard'
import { Route as AuthenticatedOrgOrgSlugOfficerCommunicationsRouteImport } from './routes/_authenticated/org/$orgSlug/officer/communications'
import { Route as AuthenticatedOrgOrgSlugOfficerApplicationsRouteImport } from './routes/_authenticated/org/$orgSlug/officer/applications'
import { Route as AuthenticatedOrgOrgSlugEventsEventIdRouteImport } from './routes/_authenticated/org/$orgSlug/events/$eventId'
import { Route as AuthenticatedOrgOrgSlugOfficerTrainingIndexRouteImport } from './routes/_authenticated/org/$orgSlug/officer/training/index'
import { Route as AuthenticatedOrgOrgSlugOfficerRosterIndexRouteImport } from './routes/_authenticated/org/$orgSlug/officer/roster/index'
import { Route as AuthenticatedOrgOrgSlugOfficerPaymentsIndexRouteImport } from './routes/_authenticated/org/$orgSlug/officer/payments/index'
import { Route as AuthenticatedOrgOrgSlugOfficerEventsIndexRouteImport } from './routes/_authenticated/org/$orgSlug/officer/events/index'
import { Route as AuthenticatedOrgOrgSlugOfficerElectionsIndexRouteImport } from './routes/_authenticated/org/$orgSlug/officer/elections/index'
import { Route as AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRouteImport } from './routes/_authenticated/org/$orgSlug/officer/communications/index'
import { Route as AuthenticatedOrgOrgSlugElectionsElectionIdIndexRouteImport } from './routes/_authenticated/org/$orgSlug/elections/$electionId/index'
import { Route as AuthenticatedOrgOrgSlugOfficerTrainingNewRouteImport } from './routes/_authenticated/org/$orgSlug/officer/training/new'
import { Route as AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteImport } from './routes/_authenticated/org/$orgSlug/officer/training/$trainingId'
import { Route as AuthenticatedOrgOrgSlugOfficerSettingsProvidersRouteImport } from './routes/_authenticated/org/$orgSlug/officer/settings/providers'
import { Route as AuthenticatedOrgOrgSlugOfficerSettingsOrgRouteImport } from './routes/_authenticated/org/$orgSlug/officer/settings/org'
import { Route as AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRouteImport } from './routes/_authenticated/org/$orgSlug/officer/settings/membership-categories'
import { Route as AuthenticatedOrgOrgSlugOfficerSettingsGatewayRouteImport } from './routes/_authenticated/org/$orgSlug/officer/settings/gateway'
import { Route as AuthenticatedOrgOrgSlugOfficerSettingsFundsRouteImport } from './routes/_authenticated/org/$orgSlug/officer/settings/funds'
import { Route as AuthenticatedOrgOrgSlugOfficerSettingsDuesRouteImport } from './routes/_authenticated/org/$orgSlug/officer/settings/dues'
import { Route as AuthenticatedOrgOrgSlugOfficerSettingsChaptersRouteImport } from './routes/_authenticated/org/$orgSlug/officer/settings/chapters'
import { Route as AuthenticatedOrgOrgSlugOfficerRosterImportRouteImport } from './routes/_authenticated/org/$orgSlug/officer/roster/import'
import { Route as AuthenticatedOrgOrgSlugOfficerRosterMemberIdRouteImport } from './routes/_authenticated/org/$orgSlug/officer/roster/$memberId'
import { Route as AuthenticatedOrgOrgSlugOfficerReportsFinancialRouteImport } from './routes/_authenticated/org/$orgSlug/officer/reports/financial'
import { Route as AuthenticatedOrgOrgSlugOfficerReportsCreditsRouteImport } from './routes/_authenticated/org/$orgSlug/officer/reports/credits'
import { Route as AuthenticatedOrgOrgSlugOfficerPaymentsNewRouteImport } from './routes/_authenticated/org/$orgSlug/officer/payments/new'
import { Route as AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRouteImport } from './routes/_authenticated/org/$orgSlug/officer/payments/$paymentId'
import { Route as AuthenticatedOrgOrgSlugOfficerEventsNewRouteImport } from './routes/_authenticated/org/$orgSlug/officer/events/new'
import { Route as AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteImport } from './routes/_authenticated/org/$orgSlug/officer/events/$eventId'
import { Route as AuthenticatedOrgOrgSlugOfficerElectionsNewRouteImport } from './routes/_authenticated/org/$orgSlug/officer/elections/new'
import { Route as AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteImport } from './routes/_authenticated/org/$orgSlug/officer/elections/$electionId'
import { Route as AuthenticatedOrgOrgSlugOfficerCommunicationsNewRouteImport } from './routes/_authenticated/org/$orgSlug/officer/communications/new'
import { Route as AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRouteImport } from './routes/_authenticated/org/$orgSlug/officer/communications/$announcementId'
import { Route as AuthenticatedOrgOrgSlugElectionsElectionIdVoteRouteImport } from './routes/_authenticated/org/$orgSlug/elections/$electionId/vote'
import { Route as AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRouteImport } from './routes/_authenticated/org/$orgSlug/officer/training/$trainingId/attendance'
import { Route as AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRouteImport } from './routes/_authenticated/org/$orgSlug/officer/events/$eventId/attendance'
import { Route as AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRouteImport } from './routes/_authenticated/org/$orgSlug/officer/elections/$electionId/edit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyTrainingRoute = AuthenticatedMyTrainingRouteImport.update({
  id: '/my/training',
  path: '/my/training',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMySettingsRoute = AuthenticatedMySettingsRouteImport.update({
  id: '/my/settings',
  path: '/my/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyProfileRoute = AuthenticatedMyProfileRouteImport.update({
  id: '/my/profile',
  path: '/my/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyPaymentsRoute = AuthenticatedMyPaymentsRouteImport.update({
  id: '/my/payments',
  path: '/my/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyOrganizationsRoute =
  AuthenticatedMyOrganizationsRouteImport.update({
    id: '/my/organizations',
    path: '/my/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyNotificationsRoute =
  AuthenticatedMyNotificationsRouteImport.update({
    id: '/my/notifications',
    path: '/my/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyIdCardRoute = AuthenticatedMyIdCardRouteImport.update({
  id: '/my/id-card',
  path: '/my/id-card',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyEventsRoute = AuthenticatedMyEventsRouteImport.update({
  id: '/my/events',
  path: '/my/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyDataExportRoute =
  AuthenticatedMyDataExportRouteImport.update({
    id: '/my/data-export',
    path: '/my/data-export',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgOrgSlugRouteRoute =
  AuthenticatedOrgOrgSlugRouteRouteImport.update({
    id: '/org/$orgSlug',
    path: '/org/$orgSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyCreditsIndexRoute =
  AuthenticatedMyCreditsIndexRouteImport.update({
    id: '/my/credits/',
    path: '/my/credits/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyCertificatesIndexRoute =
  AuthenticatedMyCertificatesIndexRouteImport.update({
    id: '/my/certificates/',
    path: '/my/certificates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerRoute =
  AuthenticatedOrgOrgSlugOfficerRouteImport.update({
    id: '/officer',
    path: '/officer',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugMembersRoute =
  AuthenticatedOrgOrgSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugHomeRoute =
  AuthenticatedOrgOrgSlugHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugDuesRoute =
  AuthenticatedOrgOrgSlugDuesRouteImport.update({
    id: '/dues',
    path: '/dues',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedMyCreditsLogRoute =
  AuthenticatedMyCreditsLogRouteImport.update({
    id: '/my/credits/log',
    path: '/my/credits/log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyCertificatesCertificateIdRoute =
  AuthenticatedMyCertificatesCertificateIdRouteImport.update({
    id: '/my/certificates/$certificateId',
    path: '/my/certificates/$certificateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgOrgSlugTrainingIndexRoute =
  AuthenticatedOrgOrgSlugTrainingIndexRouteImport.update({
    id: '/training/',
    path: '/training/',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugEventsIndexRoute =
  AuthenticatedOrgOrgSlugEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugElectionsIndexRoute =
  AuthenticatedOrgOrgSlugElectionsIndexRouteImport.update({
    id: '/elections/',
    path: '/elections/',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugTrainingTrainingIdRoute =
  AuthenticatedOrgOrgSlugTrainingTrainingIdRouteImport.update({
    id: '/training/$trainingId',
    path: '/training/$trainingId',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerRosterRoute =
  AuthenticatedOrgOrgSlugOfficerRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerPaymentsRoute =
  AuthenticatedOrgOrgSlugOfficerPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerOfficersRoute =
  AuthenticatedOrgOrgSlugOfficerOfficersRouteImport.update({
    id: '/officers',
    path: '/officers',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerDashboardRoute =
  AuthenticatedOrgOrgSlugOfficerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerCommunicationsRoute =
  AuthenticatedOrgOrgSlugOfficerCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerApplicationsRoute =
  AuthenticatedOrgOrgSlugOfficerApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugEventsEventIdRoute =
  AuthenticatedOrgOrgSlugEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerTrainingIndexRoute =
  AuthenticatedOrgOrgSlugOfficerTrainingIndexRouteImport.update({
    id: '/training/',
    path: '/training/',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerRosterIndexRoute =
  AuthenticatedOrgOrgSlugOfficerRosterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRosterRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerPaymentsIndexRoute =
  AuthenticatedOrgOrgSlugOfficerPaymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerPaymentsRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerEventsIndexRoute =
  AuthenticatedOrgOrgSlugOfficerEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerElectionsIndexRoute =
  AuthenticatedOrgOrgSlugOfficerElectionsIndexRouteImport.update({
    id: '/elections/',
    path: '/elections/',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRoute =
  AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerCommunicationsRoute,
  } as any)
const AuthenticatedOrgOrgSlugElectionsElectionIdIndexRoute =
  AuthenticatedOrgOrgSlugElectionsElectionIdIndexRouteImport.update({
    id: '/elections/$electionId/',
    path: '/elections/$electionId/',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerTrainingNewRoute =
  AuthenticatedOrgOrgSlugOfficerTrainingNewRouteImport.update({
    id: '/training/new',
    path: '/training/new',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRoute =
  AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteImport.update({
    id: '/training/$trainingId',
    path: '/training/$trainingId',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerSettingsProvidersRoute =
  AuthenticatedOrgOrgSlugOfficerSettingsProvidersRouteImport.update({
    id: '/settings/providers',
    path: '/settings/providers',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerSettingsOrgRoute =
  AuthenticatedOrgOrgSlugOfficerSettingsOrgRouteImport.update({
    id: '/settings/org',
    path: '/settings/org',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRoute =
  AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRouteImport.update({
    id: '/settings/membership-categories',
    path: '/settings/membership-categories',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerSettingsGatewayRoute =
  AuthenticatedOrgOrgSlugOfficerSettingsGatewayRouteImport.update({
    id: '/settings/gateway',
    path: '/settings/gateway',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerSettingsFundsRoute =
  AuthenticatedOrgOrgSlugOfficerSettingsFundsRouteImport.update({
    id: '/settings/funds',
    path: '/settings/funds',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerSettingsDuesRoute =
  AuthenticatedOrgOrgSlugOfficerSettingsDuesRouteImport.update({
    id: '/settings/dues',
    path: '/settings/dues',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerSettingsChaptersRoute =
  AuthenticatedOrgOrgSlugOfficerSettingsChaptersRouteImport.update({
    id: '/settings/chapters',
    path: '/settings/chapters',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerRosterImportRoute =
  AuthenticatedOrgOrgSlugOfficerRosterImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRosterRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerRosterMemberIdRoute =
  AuthenticatedOrgOrgSlugOfficerRosterMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRosterRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerReportsFinancialRoute =
  AuthenticatedOrgOrgSlugOfficerReportsFinancialRouteImport.update({
    id: '/reports/financial',
    path: '/reports/financial',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerReportsCreditsRoute =
  AuthenticatedOrgOrgSlugOfficerReportsCreditsRouteImport.update({
    id: '/reports/credits',
    path: '/reports/credits',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerPaymentsNewRoute =
  AuthenticatedOrgOrgSlugOfficerPaymentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerPaymentsRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRoute =
  AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRouteImport.update({
    id: '/$paymentId',
    path: '/$paymentId',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerPaymentsRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerEventsNewRoute =
  AuthenticatedOrgOrgSlugOfficerEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerEventsEventIdRoute =
  AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerElectionsNewRoute =
  AuthenticatedOrgOrgSlugOfficerElectionsNewRouteImport.update({
    id: '/elections/new',
    path: '/elections/new',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRoute =
  AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteImport.update({
    id: '/elections/$electionId',
    path: '/elections/$electionId',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerCommunicationsNewRoute =
  AuthenticatedOrgOrgSlugOfficerCommunicationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerCommunicationsRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRoute =
  AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRouteImport.update({
    id: '/$announcementId',
    path: '/$announcementId',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerCommunicationsRoute,
  } as any)
const AuthenticatedOrgOrgSlugElectionsElectionIdVoteRoute =
  AuthenticatedOrgOrgSlugElectionsElectionIdVoteRouteImport.update({
    id: '/elections/$electionId/vote',
    path: '/elections/$electionId/vote',
    getParentRoute: () => AuthenticatedOrgOrgSlugRouteRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRoute =
  AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRoute =
  AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedOrgOrgSlugOfficerEventsEventIdRoute,
  } as any)
const AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRoute =
  AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () =>
      AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$slug': typeof OrgSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/org/$orgSlug': typeof AuthenticatedOrgOrgSlugRouteRouteWithChildren
  '/my/data-export': typeof AuthenticatedMyDataExportRoute
  '/my/events': typeof AuthenticatedMyEventsRoute
  '/my/id-card': typeof AuthenticatedMyIdCardRoute
  '/my/notifications': typeof AuthenticatedMyNotificationsRoute
  '/my/organizations': typeof AuthenticatedMyOrganizationsRoute
  '/my/payments': typeof AuthenticatedMyPaymentsRoute
  '/my/profile': typeof AuthenticatedMyProfileRoute
  '/my/settings': typeof AuthenticatedMySettingsRoute
  '/my/training': typeof AuthenticatedMyTrainingRoute
  '/my/certificates/$certificateId': typeof AuthenticatedMyCertificatesCertificateIdRoute
  '/my/credits/log': typeof AuthenticatedMyCreditsLogRoute
  '/org/$orgSlug/dues': typeof AuthenticatedOrgOrgSlugDuesRoute
  '/org/$orgSlug/home': typeof AuthenticatedOrgOrgSlugHomeRoute
  '/org/$orgSlug/members': typeof AuthenticatedOrgOrgSlugMembersRoute
  '/org/$orgSlug/officer': typeof AuthenticatedOrgOrgSlugOfficerRouteWithChildren
  '/my/certificates': typeof AuthenticatedMyCertificatesIndexRoute
  '/my/credits': typeof AuthenticatedMyCreditsIndexRoute
  '/org/$orgSlug/events/$eventId': typeof AuthenticatedOrgOrgSlugEventsEventIdRoute
  '/org/$orgSlug/officer/applications': typeof AuthenticatedOrgOrgSlugOfficerApplicationsRoute
  '/org/$orgSlug/officer/communications': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsRouteWithChildren
  '/org/$orgSlug/officer/dashboard': typeof AuthenticatedOrgOrgSlugOfficerDashboardRoute
  '/org/$orgSlug/officer/officers': typeof AuthenticatedOrgOrgSlugOfficerOfficersRoute
  '/org/$orgSlug/officer/payments': typeof AuthenticatedOrgOrgSlugOfficerPaymentsRouteWithChildren
  '/org/$orgSlug/officer/roster': typeof AuthenticatedOrgOrgSlugOfficerRosterRouteWithChildren
  '/org/$orgSlug/training/$trainingId': typeof AuthenticatedOrgOrgSlugTrainingTrainingIdRoute
  '/org/$orgSlug/elections': typeof AuthenticatedOrgOrgSlugElectionsIndexRoute
  '/org/$orgSlug/events': typeof AuthenticatedOrgOrgSlugEventsIndexRoute
  '/org/$orgSlug/training': typeof AuthenticatedOrgOrgSlugTrainingIndexRoute
  '/org/$orgSlug/elections/$electionId/vote': typeof AuthenticatedOrgOrgSlugElectionsElectionIdVoteRoute
  '/org/$orgSlug/officer/communications/$announcementId': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRoute
  '/org/$orgSlug/officer/communications/new': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsNewRoute
  '/org/$orgSlug/officer/elections/$electionId': typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteWithChildren
  '/org/$orgSlug/officer/elections/new': typeof AuthenticatedOrgOrgSlugOfficerElectionsNewRoute
  '/org/$orgSlug/officer/events/$eventId': typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteWithChildren
  '/org/$orgSlug/officer/events/new': typeof AuthenticatedOrgOrgSlugOfficerEventsNewRoute
  '/org/$orgSlug/officer/payments/$paymentId': typeof AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRoute
  '/org/$orgSlug/officer/payments/new': typeof AuthenticatedOrgOrgSlugOfficerPaymentsNewRoute
  '/org/$orgSlug/officer/reports/credits': typeof AuthenticatedOrgOrgSlugOfficerReportsCreditsRoute
  '/org/$orgSlug/officer/reports/financial': typeof AuthenticatedOrgOrgSlugOfficerReportsFinancialRoute
  '/org/$orgSlug/officer/roster/$memberId': typeof AuthenticatedOrgOrgSlugOfficerRosterMemberIdRoute
  '/org/$orgSlug/officer/roster/import': typeof AuthenticatedOrgOrgSlugOfficerRosterImportRoute
  '/org/$orgSlug/officer/settings/chapters': typeof AuthenticatedOrgOrgSlugOfficerSettingsChaptersRoute
  '/org/$orgSlug/officer/settings/dues': typeof AuthenticatedOrgOrgSlugOfficerSettingsDuesRoute
  '/org/$orgSlug/officer/settings/funds': typeof AuthenticatedOrgOrgSlugOfficerSettingsFundsRoute
  '/org/$orgSlug/officer/settings/gateway': typeof AuthenticatedOrgOrgSlugOfficerSettingsGatewayRoute
  '/org/$orgSlug/officer/settings/membership-categories': typeof AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRoute
  '/org/$orgSlug/officer/settings/org': typeof AuthenticatedOrgOrgSlugOfficerSettingsOrgRoute
  '/org/$orgSlug/officer/settings/providers': typeof AuthenticatedOrgOrgSlugOfficerSettingsProvidersRoute
  '/org/$orgSlug/officer/training/$trainingId': typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteWithChildren
  '/org/$orgSlug/officer/training/new': typeof AuthenticatedOrgOrgSlugOfficerTrainingNewRoute
  '/org/$orgSlug/elections/$electionId': typeof AuthenticatedOrgOrgSlugElectionsElectionIdIndexRoute
  '/org/$orgSlug/officer/communications/': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRoute
  '/org/$orgSlug/officer/elections': typeof AuthenticatedOrgOrgSlugOfficerElectionsIndexRoute
  '/org/$orgSlug/officer/events': typeof AuthenticatedOrgOrgSlugOfficerEventsIndexRoute
  '/org/$orgSlug/officer/payments/': typeof AuthenticatedOrgOrgSlugOfficerPaymentsIndexRoute
  '/org/$orgSlug/officer/roster/': typeof AuthenticatedOrgOrgSlugOfficerRosterIndexRoute
  '/org/$orgSlug/officer/training': typeof AuthenticatedOrgOrgSlugOfficerTrainingIndexRoute
  '/org/$orgSlug/officer/elections/$electionId/edit': typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRoute
  '/org/$orgSlug/officer/events/$eventId/attendance': typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRoute
  '/org/$orgSlug/officer/training/$trainingId/attendance': typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$slug': typeof OrgSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/org/$orgSlug': typeof AuthenticatedOrgOrgSlugRouteRouteWithChildren
  '/my/data-export': typeof AuthenticatedMyDataExportRoute
  '/my/events': typeof AuthenticatedMyEventsRoute
  '/my/id-card': typeof AuthenticatedMyIdCardRoute
  '/my/notifications': typeof AuthenticatedMyNotificationsRoute
  '/my/organizations': typeof AuthenticatedMyOrganizationsRoute
  '/my/payments': typeof AuthenticatedMyPaymentsRoute
  '/my/profile': typeof AuthenticatedMyProfileRoute
  '/my/settings': typeof AuthenticatedMySettingsRoute
  '/my/training': typeof AuthenticatedMyTrainingRoute
  '/my/certificates/$certificateId': typeof AuthenticatedMyCertificatesCertificateIdRoute
  '/my/credits/log': typeof AuthenticatedMyCreditsLogRoute
  '/org/$orgSlug/dues': typeof AuthenticatedOrgOrgSlugDuesRoute
  '/org/$orgSlug/home': typeof AuthenticatedOrgOrgSlugHomeRoute
  '/org/$orgSlug/members': typeof AuthenticatedOrgOrgSlugMembersRoute
  '/org/$orgSlug/officer': typeof AuthenticatedOrgOrgSlugOfficerRouteWithChildren
  '/my/certificates': typeof AuthenticatedMyCertificatesIndexRoute
  '/my/credits': typeof AuthenticatedMyCreditsIndexRoute
  '/org/$orgSlug/events/$eventId': typeof AuthenticatedOrgOrgSlugEventsEventIdRoute
  '/org/$orgSlug/officer/applications': typeof AuthenticatedOrgOrgSlugOfficerApplicationsRoute
  '/org/$orgSlug/officer/dashboard': typeof AuthenticatedOrgOrgSlugOfficerDashboardRoute
  '/org/$orgSlug/officer/officers': typeof AuthenticatedOrgOrgSlugOfficerOfficersRoute
  '/org/$orgSlug/training/$trainingId': typeof AuthenticatedOrgOrgSlugTrainingTrainingIdRoute
  '/org/$orgSlug/elections': typeof AuthenticatedOrgOrgSlugElectionsIndexRoute
  '/org/$orgSlug/events': typeof AuthenticatedOrgOrgSlugEventsIndexRoute
  '/org/$orgSlug/training': typeof AuthenticatedOrgOrgSlugTrainingIndexRoute
  '/org/$orgSlug/elections/$electionId/vote': typeof AuthenticatedOrgOrgSlugElectionsElectionIdVoteRoute
  '/org/$orgSlug/officer/communications/$announcementId': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRoute
  '/org/$orgSlug/officer/communications/new': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsNewRoute
  '/org/$orgSlug/officer/elections/$electionId': typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteWithChildren
  '/org/$orgSlug/officer/elections/new': typeof AuthenticatedOrgOrgSlugOfficerElectionsNewRoute
  '/org/$orgSlug/officer/events/$eventId': typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteWithChildren
  '/org/$orgSlug/officer/events/new': typeof AuthenticatedOrgOrgSlugOfficerEventsNewRoute
  '/org/$orgSlug/officer/payments/$paymentId': typeof AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRoute
  '/org/$orgSlug/officer/payments/new': typeof AuthenticatedOrgOrgSlugOfficerPaymentsNewRoute
  '/org/$orgSlug/officer/reports/credits': typeof AuthenticatedOrgOrgSlugOfficerReportsCreditsRoute
  '/org/$orgSlug/officer/reports/financial': typeof AuthenticatedOrgOrgSlugOfficerReportsFinancialRoute
  '/org/$orgSlug/officer/roster/$memberId': typeof AuthenticatedOrgOrgSlugOfficerRosterMemberIdRoute
  '/org/$orgSlug/officer/roster/import': typeof AuthenticatedOrgOrgSlugOfficerRosterImportRoute
  '/org/$orgSlug/officer/settings/chapters': typeof AuthenticatedOrgOrgSlugOfficerSettingsChaptersRoute
  '/org/$orgSlug/officer/settings/dues': typeof AuthenticatedOrgOrgSlugOfficerSettingsDuesRoute
  '/org/$orgSlug/officer/settings/funds': typeof AuthenticatedOrgOrgSlugOfficerSettingsFundsRoute
  '/org/$orgSlug/officer/settings/gateway': typeof AuthenticatedOrgOrgSlugOfficerSettingsGatewayRoute
  '/org/$orgSlug/officer/settings/membership-categories': typeof AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRoute
  '/org/$orgSlug/officer/settings/org': typeof AuthenticatedOrgOrgSlugOfficerSettingsOrgRoute
  '/org/$orgSlug/officer/settings/providers': typeof AuthenticatedOrgOrgSlugOfficerSettingsProvidersRoute
  '/org/$orgSlug/officer/training/$trainingId': typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteWithChildren
  '/org/$orgSlug/officer/training/new': typeof AuthenticatedOrgOrgSlugOfficerTrainingNewRoute
  '/org/$orgSlug/elections/$electionId': typeof AuthenticatedOrgOrgSlugElectionsElectionIdIndexRoute
  '/org/$orgSlug/officer/communications': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRoute
  '/org/$orgSlug/officer/elections': typeof AuthenticatedOrgOrgSlugOfficerElectionsIndexRoute
  '/org/$orgSlug/officer/events': typeof AuthenticatedOrgOrgSlugOfficerEventsIndexRoute
  '/org/$orgSlug/officer/payments': typeof AuthenticatedOrgOrgSlugOfficerPaymentsIndexRoute
  '/org/$orgSlug/officer/roster': typeof AuthenticatedOrgOrgSlugOfficerRosterIndexRoute
  '/org/$orgSlug/officer/training': typeof AuthenticatedOrgOrgSlugOfficerTrainingIndexRoute
  '/org/$orgSlug/officer/elections/$electionId/edit': typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRoute
  '/org/$orgSlug/officer/events/$eventId/attendance': typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRoute
  '/org/$orgSlug/officer/training/$trainingId/attendance': typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/org/$slug': typeof OrgSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/_authenticated/org/$orgSlug': typeof AuthenticatedOrgOrgSlugRouteRouteWithChildren
  '/_authenticated/my/data-export': typeof AuthenticatedMyDataExportRoute
  '/_authenticated/my/events': typeof AuthenticatedMyEventsRoute
  '/_authenticated/my/id-card': typeof AuthenticatedMyIdCardRoute
  '/_authenticated/my/notifications': typeof AuthenticatedMyNotificationsRoute
  '/_authenticated/my/organizations': typeof AuthenticatedMyOrganizationsRoute
  '/_authenticated/my/payments': typeof AuthenticatedMyPaymentsRoute
  '/_authenticated/my/profile': typeof AuthenticatedMyProfileRoute
  '/_authenticated/my/settings': typeof AuthenticatedMySettingsRoute
  '/_authenticated/my/training': typeof AuthenticatedMyTrainingRoute
  '/_authenticated/my/certificates/$certificateId': typeof AuthenticatedMyCertificatesCertificateIdRoute
  '/_authenticated/my/credits/log': typeof AuthenticatedMyCreditsLogRoute
  '/_authenticated/org/$orgSlug/dues': typeof AuthenticatedOrgOrgSlugDuesRoute
  '/_authenticated/org/$orgSlug/home': typeof AuthenticatedOrgOrgSlugHomeRoute
  '/_authenticated/org/$orgSlug/members': typeof AuthenticatedOrgOrgSlugMembersRoute
  '/_authenticated/org/$orgSlug/officer': typeof AuthenticatedOrgOrgSlugOfficerRouteWithChildren
  '/_authenticated/my/certificates/': typeof AuthenticatedMyCertificatesIndexRoute
  '/_authenticated/my/credits/': typeof AuthenticatedMyCreditsIndexRoute
  '/_authenticated/org/$orgSlug/events/$eventId': typeof AuthenticatedOrgOrgSlugEventsEventIdRoute
  '/_authenticated/org/$orgSlug/officer/applications': typeof AuthenticatedOrgOrgSlugOfficerApplicationsRoute
  '/_authenticated/org/$orgSlug/officer/communications': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsRouteWithChildren
  '/_authenticated/org/$orgSlug/officer/dashboard': typeof AuthenticatedOrgOrgSlugOfficerDashboardRoute
  '/_authenticated/org/$orgSlug/officer/officers': typeof AuthenticatedOrgOrgSlugOfficerOfficersRoute
  '/_authenticated/org/$orgSlug/officer/payments': typeof AuthenticatedOrgOrgSlugOfficerPaymentsRouteWithChildren
  '/_authenticated/org/$orgSlug/officer/roster': typeof AuthenticatedOrgOrgSlugOfficerRosterRouteWithChildren
  '/_authenticated/org/$orgSlug/training/$trainingId': typeof AuthenticatedOrgOrgSlugTrainingTrainingIdRoute
  '/_authenticated/org/$orgSlug/elections/': typeof AuthenticatedOrgOrgSlugElectionsIndexRoute
  '/_authenticated/org/$orgSlug/events/': typeof AuthenticatedOrgOrgSlugEventsIndexRoute
  '/_authenticated/org/$orgSlug/training/': typeof AuthenticatedOrgOrgSlugTrainingIndexRoute
  '/_authenticated/org/$orgSlug/elections/$electionId/vote': typeof AuthenticatedOrgOrgSlugElectionsElectionIdVoteRoute
  '/_authenticated/org/$orgSlug/officer/communications/$announcementId': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRoute
  '/_authenticated/org/$orgSlug/officer/communications/new': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsNewRoute
  '/_authenticated/org/$orgSlug/officer/elections/$electionId': typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteWithChildren
  '/_authenticated/org/$orgSlug/officer/elections/new': typeof AuthenticatedOrgOrgSlugOfficerElectionsNewRoute
  '/_authenticated/org/$orgSlug/officer/events/$eventId': typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteWithChildren
  '/_authenticated/org/$orgSlug/officer/events/new': typeof AuthenticatedOrgOrgSlugOfficerEventsNewRoute
  '/_authenticated/org/$orgSlug/officer/payments/$paymentId': typeof AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRoute
  '/_authenticated/org/$orgSlug/officer/payments/new': typeof AuthenticatedOrgOrgSlugOfficerPaymentsNewRoute
  '/_authenticated/org/$orgSlug/officer/reports/credits': typeof AuthenticatedOrgOrgSlugOfficerReportsCreditsRoute
  '/_authenticated/org/$orgSlug/officer/reports/financial': typeof AuthenticatedOrgOrgSlugOfficerReportsFinancialRoute
  '/_authenticated/org/$orgSlug/officer/roster/$memberId': typeof AuthenticatedOrgOrgSlugOfficerRosterMemberIdRoute
  '/_authenticated/org/$orgSlug/officer/roster/import': typeof AuthenticatedOrgOrgSlugOfficerRosterImportRoute
  '/_authenticated/org/$orgSlug/officer/settings/chapters': typeof AuthenticatedOrgOrgSlugOfficerSettingsChaptersRoute
  '/_authenticated/org/$orgSlug/officer/settings/dues': typeof AuthenticatedOrgOrgSlugOfficerSettingsDuesRoute
  '/_authenticated/org/$orgSlug/officer/settings/funds': typeof AuthenticatedOrgOrgSlugOfficerSettingsFundsRoute
  '/_authenticated/org/$orgSlug/officer/settings/gateway': typeof AuthenticatedOrgOrgSlugOfficerSettingsGatewayRoute
  '/_authenticated/org/$orgSlug/officer/settings/membership-categories': typeof AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRoute
  '/_authenticated/org/$orgSlug/officer/settings/org': typeof AuthenticatedOrgOrgSlugOfficerSettingsOrgRoute
  '/_authenticated/org/$orgSlug/officer/settings/providers': typeof AuthenticatedOrgOrgSlugOfficerSettingsProvidersRoute
  '/_authenticated/org/$orgSlug/officer/training/$trainingId': typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteWithChildren
  '/_authenticated/org/$orgSlug/officer/training/new': typeof AuthenticatedOrgOrgSlugOfficerTrainingNewRoute
  '/_authenticated/org/$orgSlug/elections/$electionId/': typeof AuthenticatedOrgOrgSlugElectionsElectionIdIndexRoute
  '/_authenticated/org/$orgSlug/officer/communications/': typeof AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRoute
  '/_authenticated/org/$orgSlug/officer/elections/': typeof AuthenticatedOrgOrgSlugOfficerElectionsIndexRoute
  '/_authenticated/org/$orgSlug/officer/events/': typeof AuthenticatedOrgOrgSlugOfficerEventsIndexRoute
  '/_authenticated/org/$orgSlug/officer/payments/': typeof AuthenticatedOrgOrgSlugOfficerPaymentsIndexRoute
  '/_authenticated/org/$orgSlug/officer/roster/': typeof AuthenticatedOrgOrgSlugOfficerRosterIndexRoute
  '/_authenticated/org/$orgSlug/officer/training/': typeof AuthenticatedOrgOrgSlugOfficerTrainingIndexRoute
  '/_authenticated/org/$orgSlug/officer/elections/$electionId/edit': typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRoute
  '/_authenticated/org/$orgSlug/officer/events/$eventId/attendance': typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRoute
  '/_authenticated/org/$orgSlug/officer/training/$trainingId/attendance': typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/auth/$authView'
    | '/invite/$token'
    | '/org/$slug'
    | '/pay/$token'
    | '/verify/$token'
    | '/org/$orgSlug'
    | '/my/data-export'
    | '/my/events'
    | '/my/id-card'
    | '/my/notifications'
    | '/my/organizations'
    | '/my/payments'
    | '/my/profile'
    | '/my/settings'
    | '/my/training'
    | '/my/certificates/$certificateId'
    | '/my/credits/log'
    | '/org/$orgSlug/dues'
    | '/org/$orgSlug/home'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/officer'
    | '/my/certificates'
    | '/my/credits'
    | '/org/$orgSlug/events/$eventId'
    | '/org/$orgSlug/officer/applications'
    | '/org/$orgSlug/officer/communications'
    | '/org/$orgSlug/officer/dashboard'
    | '/org/$orgSlug/officer/officers'
    | '/org/$orgSlug/officer/payments'
    | '/org/$orgSlug/officer/roster'
    | '/org/$orgSlug/training/$trainingId'
    | '/org/$orgSlug/elections'
    | '/org/$orgSlug/events'
    | '/org/$orgSlug/training'
    | '/org/$orgSlug/elections/$electionId/vote'
    | '/org/$orgSlug/officer/communications/$announcementId'
    | '/org/$orgSlug/officer/communications/new'
    | '/org/$orgSlug/officer/elections/$electionId'
    | '/org/$orgSlug/officer/elections/new'
    | '/org/$orgSlug/officer/events/$eventId'
    | '/org/$orgSlug/officer/events/new'
    | '/org/$orgSlug/officer/payments/$paymentId'
    | '/org/$orgSlug/officer/payments/new'
    | '/org/$orgSlug/officer/reports/credits'
    | '/org/$orgSlug/officer/reports/financial'
    | '/org/$orgSlug/officer/roster/$memberId'
    | '/org/$orgSlug/officer/roster/import'
    | '/org/$orgSlug/officer/settings/chapters'
    | '/org/$orgSlug/officer/settings/dues'
    | '/org/$orgSlug/officer/settings/funds'
    | '/org/$orgSlug/officer/settings/gateway'
    | '/org/$orgSlug/officer/settings/membership-categories'
    | '/org/$orgSlug/officer/settings/org'
    | '/org/$orgSlug/officer/settings/providers'
    | '/org/$orgSlug/officer/training/$trainingId'
    | '/org/$orgSlug/officer/training/new'
    | '/org/$orgSlug/elections/$electionId'
    | '/org/$orgSlug/officer/communications/'
    | '/org/$orgSlug/officer/elections'
    | '/org/$orgSlug/officer/events'
    | '/org/$orgSlug/officer/payments/'
    | '/org/$orgSlug/officer/roster/'
    | '/org/$orgSlug/officer/training'
    | '/org/$orgSlug/officer/elections/$electionId/edit'
    | '/org/$orgSlug/officer/events/$eventId/attendance'
    | '/org/$orgSlug/officer/training/$trainingId/attendance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/auth/$authView'
    | '/invite/$token'
    | '/org/$slug'
    | '/pay/$token'
    | '/verify/$token'
    | '/org/$orgSlug'
    | '/my/data-export'
    | '/my/events'
    | '/my/id-card'
    | '/my/notifications'
    | '/my/organizations'
    | '/my/payments'
    | '/my/profile'
    | '/my/settings'
    | '/my/training'
    | '/my/certificates/$certificateId'
    | '/my/credits/log'
    | '/org/$orgSlug/dues'
    | '/org/$orgSlug/home'
    | '/org/$orgSlug/members'
    | '/org/$orgSlug/officer'
    | '/my/certificates'
    | '/my/credits'
    | '/org/$orgSlug/events/$eventId'
    | '/org/$orgSlug/officer/applications'
    | '/org/$orgSlug/officer/dashboard'
    | '/org/$orgSlug/officer/officers'
    | '/org/$orgSlug/training/$trainingId'
    | '/org/$orgSlug/elections'
    | '/org/$orgSlug/events'
    | '/org/$orgSlug/training'
    | '/org/$orgSlug/elections/$electionId/vote'
    | '/org/$orgSlug/officer/communications/$announcementId'
    | '/org/$orgSlug/officer/communications/new'
    | '/org/$orgSlug/officer/elections/$electionId'
    | '/org/$orgSlug/officer/elections/new'
    | '/org/$orgSlug/officer/events/$eventId'
    | '/org/$orgSlug/officer/events/new'
    | '/org/$orgSlug/officer/payments/$paymentId'
    | '/org/$orgSlug/officer/payments/new'
    | '/org/$orgSlug/officer/reports/credits'
    | '/org/$orgSlug/officer/reports/financial'
    | '/org/$orgSlug/officer/roster/$memberId'
    | '/org/$orgSlug/officer/roster/import'
    | '/org/$orgSlug/officer/settings/chapters'
    | '/org/$orgSlug/officer/settings/dues'
    | '/org/$orgSlug/officer/settings/funds'
    | '/org/$orgSlug/officer/settings/gateway'
    | '/org/$orgSlug/officer/settings/membership-categories'
    | '/org/$orgSlug/officer/settings/org'
    | '/org/$orgSlug/officer/settings/providers'
    | '/org/$orgSlug/officer/training/$trainingId'
    | '/org/$orgSlug/officer/training/new'
    | '/org/$orgSlug/elections/$electionId'
    | '/org/$orgSlug/officer/communications'
    | '/org/$orgSlug/officer/elections'
    | '/org/$orgSlug/officer/events'
    | '/org/$orgSlug/officer/payments'
    | '/org/$orgSlug/officer/roster'
    | '/org/$orgSlug/officer/training'
    | '/org/$orgSlug/officer/elections/$electionId/edit'
    | '/org/$orgSlug/officer/events/$eventId/attendance'
    | '/org/$orgSlug/officer/training/$trainingId/attendance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/onboarding'
    | '/_authenticated/dashboard'
    | '/auth/$authView'
    | '/invite/$token'
    | '/org/$slug'
    | '/pay/$token'
    | '/verify/$token'
    | '/_authenticated/org/$orgSlug'
    | '/_authenticated/my/data-export'
    | '/_authenticated/my/events'
    | '/_authenticated/my/id-card'
    | '/_authenticated/my/notifications'
    | '/_authenticated/my/organizations'
    | '/_authenticated/my/payments'
    | '/_authenticated/my/profile'
    | '/_authenticated/my/settings'
    | '/_authenticated/my/training'
    | '/_authenticated/my/certificates/$certificateId'
    | '/_authenticated/my/credits/log'
    | '/_authenticated/org/$orgSlug/dues'
    | '/_authenticated/org/$orgSlug/home'
    | '/_authenticated/org/$orgSlug/members'
    | '/_authenticated/org/$orgSlug/officer'
    | '/_authenticated/my/certificates/'
    | '/_authenticated/my/credits/'
    | '/_authenticated/org/$orgSlug/events/$eventId'
    | '/_authenticated/org/$orgSlug/officer/applications'
    | '/_authenticated/org/$orgSlug/officer/communications'
    | '/_authenticated/org/$orgSlug/officer/dashboard'
    | '/_authenticated/org/$orgSlug/officer/officers'
    | '/_authenticated/org/$orgSlug/officer/payments'
    | '/_authenticated/org/$orgSlug/officer/roster'
    | '/_authenticated/org/$orgSlug/training/$trainingId'
    | '/_authenticated/org/$orgSlug/elections/'
    | '/_authenticated/org/$orgSlug/events/'
    | '/_authenticated/org/$orgSlug/training/'
    | '/_authenticated/org/$orgSlug/elections/$electionId/vote'
    | '/_authenticated/org/$orgSlug/officer/communications/$announcementId'
    | '/_authenticated/org/$orgSlug/officer/communications/new'
    | '/_authenticated/org/$orgSlug/officer/elections/$electionId'
    | '/_authenticated/org/$orgSlug/officer/elections/new'
    | '/_authenticated/org/$orgSlug/officer/events/$eventId'
    | '/_authenticated/org/$orgSlug/officer/events/new'
    | '/_authenticated/org/$orgSlug/officer/payments/$paymentId'
    | '/_authenticated/org/$orgSlug/officer/payments/new'
    | '/_authenticated/org/$orgSlug/officer/reports/credits'
    | '/_authenticated/org/$orgSlug/officer/reports/financial'
    | '/_authenticated/org/$orgSlug/officer/roster/$memberId'
    | '/_authenticated/org/$orgSlug/officer/roster/import'
    | '/_authenticated/org/$orgSlug/officer/settings/chapters'
    | '/_authenticated/org/$orgSlug/officer/settings/dues'
    | '/_authenticated/org/$orgSlug/officer/settings/funds'
    | '/_authenticated/org/$orgSlug/officer/settings/gateway'
    | '/_authenticated/org/$orgSlug/officer/settings/membership-categories'
    | '/_authenticated/org/$orgSlug/officer/settings/org'
    | '/_authenticated/org/$orgSlug/officer/settings/providers'
    | '/_authenticated/org/$orgSlug/officer/training/$trainingId'
    | '/_authenticated/org/$orgSlug/officer/training/new'
    | '/_authenticated/org/$orgSlug/elections/$electionId/'
    | '/_authenticated/org/$orgSlug/officer/communications/'
    | '/_authenticated/org/$orgSlug/officer/elections/'
    | '/_authenticated/org/$orgSlug/officer/events/'
    | '/_authenticated/org/$orgSlug/officer/payments/'
    | '/_authenticated/org/$orgSlug/officer/roster/'
    | '/_authenticated/org/$orgSlug/officer/training/'
    | '/_authenticated/org/$orgSlug/officer/elections/$electionId/edit'
    | '/_authenticated/org/$orgSlug/officer/events/$eventId/attendance'
    | '/_authenticated/org/$orgSlug/officer/training/$trainingId/attendance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OrgSlugRoute: typeof OrgSlugRoute
  PayTokenRoute: typeof PayTokenRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/training': {
      id: '/_authenticated/my/training'
      path: '/my/training'
      fullPath: '/my/training'
      preLoaderRoute: typeof AuthenticatedMyTrainingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/settings': {
      id: '/_authenticated/my/settings'
      path: '/my/settings'
      fullPath: '/my/settings'
      preLoaderRoute: typeof AuthenticatedMySettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/profile': {
      id: '/_authenticated/my/profile'
      path: '/my/profile'
      fullPath: '/my/profile'
      preLoaderRoute: typeof AuthenticatedMyProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/payments': {
      id: '/_authenticated/my/payments'
      path: '/my/payments'
      fullPath: '/my/payments'
      preLoaderRoute: typeof AuthenticatedMyPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/organizations': {
      id: '/_authenticated/my/organizations'
      path: '/my/organizations'
      fullPath: '/my/organizations'
      preLoaderRoute: typeof AuthenticatedMyOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/notifications': {
      id: '/_authenticated/my/notifications'
      path: '/my/notifications'
      fullPath: '/my/notifications'
      preLoaderRoute: typeof AuthenticatedMyNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/id-card': {
      id: '/_authenticated/my/id-card'
      path: '/my/id-card'
      fullPath: '/my/id-card'
      preLoaderRoute: typeof AuthenticatedMyIdCardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/events': {
      id: '/_authenticated/my/events'
      path: '/my/events'
      fullPath: '/my/events'
      preLoaderRoute: typeof AuthenticatedMyEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/data-export': {
      id: '/_authenticated/my/data-export'
      path: '/my/data-export'
      fullPath: '/my/data-export'
      preLoaderRoute: typeof AuthenticatedMyDataExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org/$orgSlug': {
      id: '/_authenticated/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/credits/': {
      id: '/_authenticated/my/credits/'
      path: '/my/credits'
      fullPath: '/my/credits'
      preLoaderRoute: typeof AuthenticatedMyCreditsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/certificates/': {
      id: '/_authenticated/my/certificates/'
      path: '/my/certificates'
      fullPath: '/my/certificates'
      preLoaderRoute: typeof AuthenticatedMyCertificatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org/$orgSlug/officer': {
      id: '/_authenticated/org/$orgSlug/officer'
      path: '/officer'
      fullPath: '/org/$orgSlug/officer'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/members': {
      id: '/_authenticated/org/$orgSlug/members'
      path: '/members'
      fullPath: '/org/$orgSlug/members'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugMembersRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/home': {
      id: '/_authenticated/org/$orgSlug/home'
      path: '/home'
      fullPath: '/org/$orgSlug/home'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugHomeRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/dues': {
      id: '/_authenticated/org/$orgSlug/dues'
      path: '/dues'
      fullPath: '/org/$orgSlug/dues'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugDuesRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/my/credits/log': {
      id: '/_authenticated/my/credits/log'
      path: '/my/credits/log'
      fullPath: '/my/credits/log'
      preLoaderRoute: typeof AuthenticatedMyCreditsLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my/certificates/$certificateId': {
      id: '/_authenticated/my/certificates/$certificateId'
      path: '/my/certificates/$certificateId'
      fullPath: '/my/certificates/$certificateId'
      preLoaderRoute: typeof AuthenticatedMyCertificatesCertificateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org/$orgSlug/training/': {
      id: '/_authenticated/org/$orgSlug/training/'
      path: '/training'
      fullPath: '/org/$orgSlug/training'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/events/': {
      id: '/_authenticated/org/$orgSlug/events/'
      path: '/events'
      fullPath: '/org/$orgSlug/events'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugEventsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/elections/': {
      id: '/_authenticated/org/$orgSlug/elections/'
      path: '/elections'
      fullPath: '/org/$orgSlug/elections'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugElectionsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/training/$trainingId': {
      id: '/_authenticated/org/$orgSlug/training/$trainingId'
      path: '/training/$trainingId'
      fullPath: '/org/$orgSlug/training/$trainingId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugTrainingTrainingIdRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/officer/roster': {
      id: '/_authenticated/org/$orgSlug/officer/roster'
      path: '/roster'
      fullPath: '/org/$orgSlug/officer/roster'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/payments': {
      id: '/_authenticated/org/$orgSlug/officer/payments'
      path: '/payments'
      fullPath: '/org/$orgSlug/officer/payments'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/officers': {
      id: '/_authenticated/org/$orgSlug/officer/officers'
      path: '/officers'
      fullPath: '/org/$orgSlug/officer/officers'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerOfficersRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/dashboard': {
      id: '/_authenticated/org/$orgSlug/officer/dashboard'
      path: '/dashboard'
      fullPath: '/org/$orgSlug/officer/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerDashboardRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/communications': {
      id: '/_authenticated/org/$orgSlug/officer/communications'
      path: '/communications'
      fullPath: '/org/$orgSlug/officer/communications'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/applications': {
      id: '/_authenticated/org/$orgSlug/officer/applications'
      path: '/applications'
      fullPath: '/org/$orgSlug/officer/applications'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerApplicationsRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/events/$eventId': {
      id: '/_authenticated/org/$orgSlug/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/org/$orgSlug/events/$eventId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/officer/training/': {
      id: '/_authenticated/org/$orgSlug/officer/training/'
      path: '/training'
      fullPath: '/org/$orgSlug/officer/training'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/roster/': {
      id: '/_authenticated/org/$orgSlug/officer/roster/'
      path: '/'
      fullPath: '/org/$orgSlug/officer/roster/'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterRoute
    }
    '/_authenticated/org/$orgSlug/officer/payments/': {
      id: '/_authenticated/org/$orgSlug/officer/payments/'
      path: '/'
      fullPath: '/org/$orgSlug/officer/payments/'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsRoute
    }
    '/_authenticated/org/$orgSlug/officer/events/': {
      id: '/_authenticated/org/$orgSlug/officer/events/'
      path: '/events'
      fullPath: '/org/$orgSlug/officer/events'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/elections/': {
      id: '/_authenticated/org/$orgSlug/officer/elections/'
      path: '/elections'
      fullPath: '/org/$orgSlug/officer/elections'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/communications/': {
      id: '/_authenticated/org/$orgSlug/officer/communications/'
      path: '/'
      fullPath: '/org/$orgSlug/officer/communications/'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsRoute
    }
    '/_authenticated/org/$orgSlug/elections/$electionId/': {
      id: '/_authenticated/org/$orgSlug/elections/$electionId/'
      path: '/elections/$electionId'
      fullPath: '/org/$orgSlug/elections/$electionId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugElectionsElectionIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/officer/training/new': {
      id: '/_authenticated/org/$orgSlug/officer/training/new'
      path: '/training/new'
      fullPath: '/org/$orgSlug/officer/training/new'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingNewRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/training/$trainingId': {
      id: '/_authenticated/org/$orgSlug/officer/training/$trainingId'
      path: '/training/$trainingId'
      fullPath: '/org/$orgSlug/officer/training/$trainingId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/settings/providers': {
      id: '/_authenticated/org/$orgSlug/officer/settings/providers'
      path: '/settings/providers'
      fullPath: '/org/$orgSlug/officer/settings/providers'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsProvidersRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/settings/org': {
      id: '/_authenticated/org/$orgSlug/officer/settings/org'
      path: '/settings/org'
      fullPath: '/org/$orgSlug/officer/settings/org'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsOrgRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/settings/membership-categories': {
      id: '/_authenticated/org/$orgSlug/officer/settings/membership-categories'
      path: '/settings/membership-categories'
      fullPath: '/org/$orgSlug/officer/settings/membership-categories'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/settings/gateway': {
      id: '/_authenticated/org/$orgSlug/officer/settings/gateway'
      path: '/settings/gateway'
      fullPath: '/org/$orgSlug/officer/settings/gateway'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsGatewayRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/settings/funds': {
      id: '/_authenticated/org/$orgSlug/officer/settings/funds'
      path: '/settings/funds'
      fullPath: '/org/$orgSlug/officer/settings/funds'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsFundsRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/settings/dues': {
      id: '/_authenticated/org/$orgSlug/officer/settings/dues'
      path: '/settings/dues'
      fullPath: '/org/$orgSlug/officer/settings/dues'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsDuesRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/settings/chapters': {
      id: '/_authenticated/org/$orgSlug/officer/settings/chapters'
      path: '/settings/chapters'
      fullPath: '/org/$orgSlug/officer/settings/chapters'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsChaptersRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/roster/import': {
      id: '/_authenticated/org/$orgSlug/officer/roster/import'
      path: '/import'
      fullPath: '/org/$orgSlug/officer/roster/import'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterImportRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterRoute
    }
    '/_authenticated/org/$orgSlug/officer/roster/$memberId': {
      id: '/_authenticated/org/$orgSlug/officer/roster/$memberId'
      path: '/$memberId'
      fullPath: '/org/$orgSlug/officer/roster/$memberId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterMemberIdRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterRoute
    }
    '/_authenticated/org/$orgSlug/officer/reports/financial': {
      id: '/_authenticated/org/$orgSlug/officer/reports/financial'
      path: '/reports/financial'
      fullPath: '/org/$orgSlug/officer/reports/financial'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerReportsFinancialRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/reports/credits': {
      id: '/_authenticated/org/$orgSlug/officer/reports/credits'
      path: '/reports/credits'
      fullPath: '/org/$orgSlug/officer/reports/credits'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerReportsCreditsRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/payments/new': {
      id: '/_authenticated/org/$orgSlug/officer/payments/new'
      path: '/new'
      fullPath: '/org/$orgSlug/officer/payments/new'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsNewRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsRoute
    }
    '/_authenticated/org/$orgSlug/officer/payments/$paymentId': {
      id: '/_authenticated/org/$orgSlug/officer/payments/$paymentId'
      path: '/$paymentId'
      fullPath: '/org/$orgSlug/officer/payments/$paymentId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsRoute
    }
    '/_authenticated/org/$orgSlug/officer/events/new': {
      id: '/_authenticated/org/$orgSlug/officer/events/new'
      path: '/events/new'
      fullPath: '/org/$orgSlug/officer/events/new'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsNewRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/events/$eventId': {
      id: '/_authenticated/org/$orgSlug/officer/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/org/$orgSlug/officer/events/$eventId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/elections/new': {
      id: '/_authenticated/org/$orgSlug/officer/elections/new'
      path: '/elections/new'
      fullPath: '/org/$orgSlug/officer/elections/new'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsNewRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/elections/$electionId': {
      id: '/_authenticated/org/$orgSlug/officer/elections/$electionId'
      path: '/elections/$electionId'
      fullPath: '/org/$orgSlug/officer/elections/$electionId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerRoute
    }
    '/_authenticated/org/$orgSlug/officer/communications/new': {
      id: '/_authenticated/org/$orgSlug/officer/communications/new'
      path: '/new'
      fullPath: '/org/$orgSlug/officer/communications/new'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsNewRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsRoute
    }
    '/_authenticated/org/$orgSlug/officer/communications/$announcementId': {
      id: '/_authenticated/org/$orgSlug/officer/communications/$announcementId'
      path: '/$announcementId'
      fullPath: '/org/$orgSlug/officer/communications/$announcementId'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsRoute
    }
    '/_authenticated/org/$orgSlug/elections/$electionId/vote': {
      id: '/_authenticated/org/$orgSlug/elections/$electionId/vote'
      path: '/elections/$electionId/vote'
      fullPath: '/org/$orgSlug/elections/$electionId/vote'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugElectionsElectionIdVoteRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugRouteRoute
    }
    '/_authenticated/org/$orgSlug/officer/training/$trainingId/attendance': {
      id: '/_authenticated/org/$orgSlug/officer/training/$trainingId/attendance'
      path: '/attendance'
      fullPath: '/org/$orgSlug/officer/training/$trainingId/attendance'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRoute
    }
    '/_authenticated/org/$orgSlug/officer/events/$eventId/attendance': {
      id: '/_authenticated/org/$orgSlug/officer/events/$eventId/attendance'
      path: '/attendance'
      fullPath: '/org/$orgSlug/officer/events/$eventId/attendance'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdRoute
    }
    '/_authenticated/org/$orgSlug/officer/elections/$electionId/edit': {
      id: '/_authenticated/org/$orgSlug/officer/elections/$electionId/edit'
      path: '/edit'
      fullPath: '/org/$orgSlug/officer/elections/$electionId/edit'
      preLoaderRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRouteImport
      parentRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRoute
    }
  }
}

interface AuthenticatedOrgOrgSlugOfficerCommunicationsRouteChildren {
  AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRoute
  AuthenticatedOrgOrgSlugOfficerCommunicationsNewRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsNewRoute
  AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRoute
}

const AuthenticatedOrgOrgSlugOfficerCommunicationsRouteChildren: AuthenticatedOrgOrgSlugOfficerCommunicationsRouteChildren =
  {
    AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRoute:
      AuthenticatedOrgOrgSlugOfficerCommunicationsAnnouncementIdRoute,
    AuthenticatedOrgOrgSlugOfficerCommunicationsNewRoute:
      AuthenticatedOrgOrgSlugOfficerCommunicationsNewRoute,
    AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRoute:
      AuthenticatedOrgOrgSlugOfficerCommunicationsIndexRoute,
  }

const AuthenticatedOrgOrgSlugOfficerCommunicationsRouteWithChildren =
  AuthenticatedOrgOrgSlugOfficerCommunicationsRoute._addFileChildren(
    AuthenticatedOrgOrgSlugOfficerCommunicationsRouteChildren,
  )

interface AuthenticatedOrgOrgSlugOfficerPaymentsRouteChildren {
  AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRoute
  AuthenticatedOrgOrgSlugOfficerPaymentsNewRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsNewRoute
  AuthenticatedOrgOrgSlugOfficerPaymentsIndexRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsIndexRoute
}

const AuthenticatedOrgOrgSlugOfficerPaymentsRouteChildren: AuthenticatedOrgOrgSlugOfficerPaymentsRouteChildren =
  {
    AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRoute:
      AuthenticatedOrgOrgSlugOfficerPaymentsPaymentIdRoute,
    AuthenticatedOrgOrgSlugOfficerPaymentsNewRoute:
      AuthenticatedOrgOrgSlugOfficerPaymentsNewRoute,
    AuthenticatedOrgOrgSlugOfficerPaymentsIndexRoute:
      AuthenticatedOrgOrgSlugOfficerPaymentsIndexRoute,
  }

const AuthenticatedOrgOrgSlugOfficerPaymentsRouteWithChildren =
  AuthenticatedOrgOrgSlugOfficerPaymentsRoute._addFileChildren(
    AuthenticatedOrgOrgSlugOfficerPaymentsRouteChildren,
  )

interface AuthenticatedOrgOrgSlugOfficerRosterRouteChildren {
  AuthenticatedOrgOrgSlugOfficerRosterMemberIdRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterMemberIdRoute
  AuthenticatedOrgOrgSlugOfficerRosterImportRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterImportRoute
  AuthenticatedOrgOrgSlugOfficerRosterIndexRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterIndexRoute
}

const AuthenticatedOrgOrgSlugOfficerRosterRouteChildren: AuthenticatedOrgOrgSlugOfficerRosterRouteChildren =
  {
    AuthenticatedOrgOrgSlugOfficerRosterMemberIdRoute:
      AuthenticatedOrgOrgSlugOfficerRosterMemberIdRoute,
    AuthenticatedOrgOrgSlugOfficerRosterImportRoute:
      AuthenticatedOrgOrgSlugOfficerRosterImportRoute,
    AuthenticatedOrgOrgSlugOfficerRosterIndexRoute:
      AuthenticatedOrgOrgSlugOfficerRosterIndexRoute,
  }

const AuthenticatedOrgOrgSlugOfficerRosterRouteWithChildren =
  AuthenticatedOrgOrgSlugOfficerRosterRoute._addFileChildren(
    AuthenticatedOrgOrgSlugOfficerRosterRouteChildren,
  )

interface AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteChildren {
  AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRoute
}

const AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteChildren: AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteChildren =
  {
    AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRoute:
      AuthenticatedOrgOrgSlugOfficerElectionsElectionIdEditRoute,
  }

const AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteWithChildren =
  AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRoute._addFileChildren(
    AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteChildren,
  )

interface AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteChildren {
  AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRoute
}

const AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteChildren: AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteChildren =
  {
    AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRoute:
      AuthenticatedOrgOrgSlugOfficerEventsEventIdAttendanceRoute,
  }

const AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteWithChildren =
  AuthenticatedOrgOrgSlugOfficerEventsEventIdRoute._addFileChildren(
    AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteChildren,
  )

interface AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteChildren {
  AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRoute
}

const AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteChildren: AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteChildren =
  {
    AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRoute:
      AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdAttendanceRoute,
  }

const AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteWithChildren =
  AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRoute._addFileChildren(
    AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteChildren,
  )

interface AuthenticatedOrgOrgSlugOfficerRouteChildren {
  AuthenticatedOrgOrgSlugOfficerApplicationsRoute: typeof AuthenticatedOrgOrgSlugOfficerApplicationsRoute
  AuthenticatedOrgOrgSlugOfficerCommunicationsRoute: typeof AuthenticatedOrgOrgSlugOfficerCommunicationsRouteWithChildren
  AuthenticatedOrgOrgSlugOfficerDashboardRoute: typeof AuthenticatedOrgOrgSlugOfficerDashboardRoute
  AuthenticatedOrgOrgSlugOfficerOfficersRoute: typeof AuthenticatedOrgOrgSlugOfficerOfficersRoute
  AuthenticatedOrgOrgSlugOfficerPaymentsRoute: typeof AuthenticatedOrgOrgSlugOfficerPaymentsRouteWithChildren
  AuthenticatedOrgOrgSlugOfficerRosterRoute: typeof AuthenticatedOrgOrgSlugOfficerRosterRouteWithChildren
  AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteWithChildren
  AuthenticatedOrgOrgSlugOfficerElectionsNewRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsNewRoute
  AuthenticatedOrgOrgSlugOfficerEventsEventIdRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteWithChildren
  AuthenticatedOrgOrgSlugOfficerEventsNewRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsNewRoute
  AuthenticatedOrgOrgSlugOfficerReportsCreditsRoute: typeof AuthenticatedOrgOrgSlugOfficerReportsCreditsRoute
  AuthenticatedOrgOrgSlugOfficerReportsFinancialRoute: typeof AuthenticatedOrgOrgSlugOfficerReportsFinancialRoute
  AuthenticatedOrgOrgSlugOfficerSettingsChaptersRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsChaptersRoute
  AuthenticatedOrgOrgSlugOfficerSettingsDuesRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsDuesRoute
  AuthenticatedOrgOrgSlugOfficerSettingsFundsRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsFundsRoute
  AuthenticatedOrgOrgSlugOfficerSettingsGatewayRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsGatewayRoute
  AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRoute
  AuthenticatedOrgOrgSlugOfficerSettingsOrgRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsOrgRoute
  AuthenticatedOrgOrgSlugOfficerSettingsProvidersRoute: typeof AuthenticatedOrgOrgSlugOfficerSettingsProvidersRoute
  AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteWithChildren
  AuthenticatedOrgOrgSlugOfficerTrainingNewRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingNewRoute
  AuthenticatedOrgOrgSlugOfficerElectionsIndexRoute: typeof AuthenticatedOrgOrgSlugOfficerElectionsIndexRoute
  AuthenticatedOrgOrgSlugOfficerEventsIndexRoute: typeof AuthenticatedOrgOrgSlugOfficerEventsIndexRoute
  AuthenticatedOrgOrgSlugOfficerTrainingIndexRoute: typeof AuthenticatedOrgOrgSlugOfficerTrainingIndexRoute
}

const AuthenticatedOrgOrgSlugOfficerRouteChildren: AuthenticatedOrgOrgSlugOfficerRouteChildren =
  {
    AuthenticatedOrgOrgSlugOfficerApplicationsRoute:
      AuthenticatedOrgOrgSlugOfficerApplicationsRoute,
    AuthenticatedOrgOrgSlugOfficerCommunicationsRoute:
      AuthenticatedOrgOrgSlugOfficerCommunicationsRouteWithChildren,
    AuthenticatedOrgOrgSlugOfficerDashboardRoute:
      AuthenticatedOrgOrgSlugOfficerDashboardRoute,
    AuthenticatedOrgOrgSlugOfficerOfficersRoute:
      AuthenticatedOrgOrgSlugOfficerOfficersRoute,
    AuthenticatedOrgOrgSlugOfficerPaymentsRoute:
      AuthenticatedOrgOrgSlugOfficerPaymentsRouteWithChildren,
    AuthenticatedOrgOrgSlugOfficerRosterRoute:
      AuthenticatedOrgOrgSlugOfficerRosterRouteWithChildren,
    AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRoute:
      AuthenticatedOrgOrgSlugOfficerElectionsElectionIdRouteWithChildren,
    AuthenticatedOrgOrgSlugOfficerElectionsNewRoute:
      AuthenticatedOrgOrgSlugOfficerElectionsNewRoute,
    AuthenticatedOrgOrgSlugOfficerEventsEventIdRoute:
      AuthenticatedOrgOrgSlugOfficerEventsEventIdRouteWithChildren,
    AuthenticatedOrgOrgSlugOfficerEventsNewRoute:
      AuthenticatedOrgOrgSlugOfficerEventsNewRoute,
    AuthenticatedOrgOrgSlugOfficerReportsCreditsRoute:
      AuthenticatedOrgOrgSlugOfficerReportsCreditsRoute,
    AuthenticatedOrgOrgSlugOfficerReportsFinancialRoute:
      AuthenticatedOrgOrgSlugOfficerReportsFinancialRoute,
    AuthenticatedOrgOrgSlugOfficerSettingsChaptersRoute:
      AuthenticatedOrgOrgSlugOfficerSettingsChaptersRoute,
    AuthenticatedOrgOrgSlugOfficerSettingsDuesRoute:
      AuthenticatedOrgOrgSlugOfficerSettingsDuesRoute,
    AuthenticatedOrgOrgSlugOfficerSettingsFundsRoute:
      AuthenticatedOrgOrgSlugOfficerSettingsFundsRoute,
    AuthenticatedOrgOrgSlugOfficerSettingsGatewayRoute:
      AuthenticatedOrgOrgSlugOfficerSettingsGatewayRoute,
    AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRoute:
      AuthenticatedOrgOrgSlugOfficerSettingsMembershipCategoriesRoute,
    AuthenticatedOrgOrgSlugOfficerSettingsOrgRoute:
      AuthenticatedOrgOrgSlugOfficerSettingsOrgRoute,
    AuthenticatedOrgOrgSlugOfficerSettingsProvidersRoute:
      AuthenticatedOrgOrgSlugOfficerSettingsProvidersRoute,
    AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRoute:
      AuthenticatedOrgOrgSlugOfficerTrainingTrainingIdRouteWithChildren,
    AuthenticatedOrgOrgSlugOfficerTrainingNewRoute:
      AuthenticatedOrgOrgSlugOfficerTrainingNewRoute,
    AuthenticatedOrgOrgSlugOfficerElectionsIndexRoute:
      AuthenticatedOrgOrgSlugOfficerElectionsIndexRoute,
    AuthenticatedOrgOrgSlugOfficerEventsIndexRoute:
      AuthenticatedOrgOrgSlugOfficerEventsIndexRoute,
    AuthenticatedOrgOrgSlugOfficerTrainingIndexRoute:
      AuthenticatedOrgOrgSlugOfficerTrainingIndexRoute,
  }

const AuthenticatedOrgOrgSlugOfficerRouteWithChildren =
  AuthenticatedOrgOrgSlugOfficerRoute._addFileChildren(
    AuthenticatedOrgOrgSlugOfficerRouteChildren,
  )

interface AuthenticatedOrgOrgSlugRouteRouteChildren {
  AuthenticatedOrgOrgSlugDuesRoute: typeof AuthenticatedOrgOrgSlugDuesRoute
  AuthenticatedOrgOrgSlugHomeRoute: typeof AuthenticatedOrgOrgSlugHomeRoute
  AuthenticatedOrgOrgSlugMembersRoute: typeof AuthenticatedOrgOrgSlugMembersRoute
  AuthenticatedOrgOrgSlugOfficerRoute: typeof AuthenticatedOrgOrgSlugOfficerRouteWithChildren
  AuthenticatedOrgOrgSlugEventsEventIdRoute: typeof AuthenticatedOrgOrgSlugEventsEventIdRoute
  AuthenticatedOrgOrgSlugTrainingTrainingIdRoute: typeof AuthenticatedOrgOrgSlugTrainingTrainingIdRoute
  AuthenticatedOrgOrgSlugElectionsIndexRoute: typeof AuthenticatedOrgOrgSlugElectionsIndexRoute
  AuthenticatedOrgOrgSlugEventsIndexRoute: typeof AuthenticatedOrgOrgSlugEventsIndexRoute
  AuthenticatedOrgOrgSlugTrainingIndexRoute: typeof AuthenticatedOrgOrgSlugTrainingIndexRoute
  AuthenticatedOrgOrgSlugElectionsElectionIdVoteRoute: typeof AuthenticatedOrgOrgSlugElectionsElectionIdVoteRoute
  AuthenticatedOrgOrgSlugElectionsElectionIdIndexRoute: typeof AuthenticatedOrgOrgSlugElectionsElectionIdIndexRoute
}

const AuthenticatedOrgOrgSlugRouteRouteChildren: AuthenticatedOrgOrgSlugRouteRouteChildren =
  {
    AuthenticatedOrgOrgSlugDuesRoute: AuthenticatedOrgOrgSlugDuesRoute,
    AuthenticatedOrgOrgSlugHomeRoute: AuthenticatedOrgOrgSlugHomeRoute,
    AuthenticatedOrgOrgSlugMembersRoute: AuthenticatedOrgOrgSlugMembersRoute,
    AuthenticatedOrgOrgSlugOfficerRoute:
      AuthenticatedOrgOrgSlugOfficerRouteWithChildren,
    AuthenticatedOrgOrgSlugEventsEventIdRoute:
      AuthenticatedOrgOrgSlugEventsEventIdRoute,
    AuthenticatedOrgOrgSlugTrainingTrainingIdRoute:
      AuthenticatedOrgOrgSlugTrainingTrainingIdRoute,
    AuthenticatedOrgOrgSlugElectionsIndexRoute:
      AuthenticatedOrgOrgSlugElectionsIndexRoute,
    AuthenticatedOrgOrgSlugEventsIndexRoute:
      AuthenticatedOrgOrgSlugEventsIndexRoute,
    AuthenticatedOrgOrgSlugTrainingIndexRoute:
      AuthenticatedOrgOrgSlugTrainingIndexRoute,
    AuthenticatedOrgOrgSlugElectionsElectionIdVoteRoute:
      AuthenticatedOrgOrgSlugElectionsElectionIdVoteRoute,
    AuthenticatedOrgOrgSlugElectionsElectionIdIndexRoute:
      AuthenticatedOrgOrgSlugElectionsElectionIdIndexRoute,
  }

const AuthenticatedOrgOrgSlugRouteRouteWithChildren =
  AuthenticatedOrgOrgSlugRouteRoute._addFileChildren(
    AuthenticatedOrgOrgSlugRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrgOrgSlugRouteRoute: typeof AuthenticatedOrgOrgSlugRouteRouteWithChildren
  AuthenticatedMyDataExportRoute: typeof AuthenticatedMyDataExportRoute
  AuthenticatedMyEventsRoute: typeof AuthenticatedMyEventsRoute
  AuthenticatedMyIdCardRoute: typeof AuthenticatedMyIdCardRoute
  AuthenticatedMyNotificationsRoute: typeof AuthenticatedMyNotificationsRoute
  AuthenticatedMyOrganizationsRoute: typeof AuthenticatedMyOrganizationsRoute
  AuthenticatedMyPaymentsRoute: typeof AuthenticatedMyPaymentsRoute
  AuthenticatedMyProfileRoute: typeof AuthenticatedMyProfileRoute
  AuthenticatedMySettingsRoute: typeof AuthenticatedMySettingsRoute
  AuthenticatedMyTrainingRoute: typeof AuthenticatedMyTrainingRoute
  AuthenticatedMyCertificatesCertificateIdRoute: typeof AuthenticatedMyCertificatesCertificateIdRoute
  AuthenticatedMyCreditsLogRoute: typeof AuthenticatedMyCreditsLogRoute
  AuthenticatedMyCertificatesIndexRoute: typeof AuthenticatedMyCertificatesIndexRoute
  AuthenticatedMyCreditsIndexRoute: typeof AuthenticatedMyCreditsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrgOrgSlugRouteRoute:
    AuthenticatedOrgOrgSlugRouteRouteWithChildren,
  AuthenticatedMyDataExportRoute: AuthenticatedMyDataExportRoute,
  AuthenticatedMyEventsRoute: AuthenticatedMyEventsRoute,
  AuthenticatedMyIdCardRoute: AuthenticatedMyIdCardRoute,
  AuthenticatedMyNotificationsRoute: AuthenticatedMyNotificationsRoute,
  AuthenticatedMyOrganizationsRoute: AuthenticatedMyOrganizationsRoute,
  AuthenticatedMyPaymentsRoute: AuthenticatedMyPaymentsRoute,
  AuthenticatedMyProfileRoute: AuthenticatedMyProfileRoute,
  AuthenticatedMySettingsRoute: AuthenticatedMySettingsRoute,
  AuthenticatedMyTrainingRoute: AuthenticatedMyTrainingRoute,
  AuthenticatedMyCertificatesCertificateIdRoute:
    AuthenticatedMyCertificatesCertificateIdRoute,
  AuthenticatedMyCreditsLogRoute: AuthenticatedMyCreditsLogRoute,
  AuthenticatedMyCertificatesIndexRoute: AuthenticatedMyCertificatesIndexRoute,
  AuthenticatedMyCreditsIndexRoute: AuthenticatedMyCreditsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  InviteTokenRoute: InviteTokenRoute,
  OrgSlugRoute: OrgSlugRoute,
  PayTokenRoute: PayTokenRoute,
  VerifyTokenRoute: VerifyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
