/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as DashboardNotificationsRouteImport } from './routes/_dashboard/notifications'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardBookingsIndexRouteImport } from './routes/_dashboard/bookings/index'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/_dashboard/settings/security'
import { Route as DashboardSettingsScheduleRouteImport } from './routes/_dashboard/settings/schedule'
import { Route as DashboardSettingsBillingRouteImport } from './routes/_dashboard/settings/billing'
import { Route as DashboardSettingsAccountRouteImport } from './routes/_dashboard/settings/account'
import { Route as DashboardBookingsBookingIdRouteImport } from './routes/_dashboard/bookings/$bookingId'
import { Route as DashboardBookingsHostPersonIdRouteImport } from './routes/_dashboard/bookings/host.$personId'
import { Route as DashboardBookingsHostPersonIdSlotIdRouteImport } from './routes/_dashboard/bookings/host.$personId.$slotId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsIndexRoute = DashboardBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsScheduleRoute =
  DashboardSettingsScheduleRouteImport.update({
    id: '/settings/schedule',
    path: '/settings/schedule',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBookingsBookingIdRoute =
  DashboardBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBookingsHostPersonIdRoute =
  DashboardBookingsHostPersonIdRouteImport.update({
    id: '/bookings/host/$personId',
    path: '/bookings/host/$personId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBookingsHostPersonIdSlotIdRoute =
  DashboardBookingsHostPersonIdSlotIdRouteImport.update({
    id: '/$slotId',
    path: '/$slotId',
    getParentRoute: () => DashboardBookingsHostPersonIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/settings/account': typeof DashboardSettingsAccountRoute
  '/settings/billing': typeof DashboardSettingsBillingRoute
  '/settings/schedule': typeof DashboardSettingsScheduleRoute
  '/settings/security': typeof DashboardSettingsSecurityRoute
  '/bookings': typeof DashboardBookingsIndexRoute
  '/bookings/host/$personId': typeof DashboardBookingsHostPersonIdRouteWithChildren
  '/bookings/host/$personId/$slotId': typeof DashboardBookingsHostPersonIdSlotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/settings/account': typeof DashboardSettingsAccountRoute
  '/settings/billing': typeof DashboardSettingsBillingRoute
  '/settings/schedule': typeof DashboardSettingsScheduleRoute
  '/settings/security': typeof DashboardSettingsSecurityRoute
  '/bookings': typeof DashboardBookingsIndexRoute
  '/bookings/host/$personId': typeof DashboardBookingsHostPersonIdRouteWithChildren
  '/bookings/host/$personId/$slotId': typeof DashboardBookingsHostPersonIdSlotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/notifications': typeof DashboardNotificationsRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/_dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/_dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/_dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/_dashboard/settings/schedule': typeof DashboardSettingsScheduleRoute
  '/_dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/_dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/_dashboard/bookings/host/$personId': typeof DashboardBookingsHostPersonIdRouteWithChildren
  '/_dashboard/bookings/host/$personId/$slotId': typeof DashboardBookingsHostPersonIdSlotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/auth/$authView'
    | '/bookings/$bookingId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/schedule'
    | '/settings/security'
    | '/bookings'
    | '/bookings/host/$personId'
    | '/bookings/host/$personId/$slotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/auth/$authView'
    | '/bookings/$bookingId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/schedule'
    | '/settings/security'
    | '/bookings'
    | '/bookings/host/$personId'
    | '/bookings/host/$personId/$slotId'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/onboarding'
    | '/verify-email'
    | '/_dashboard/dashboard'
    | '/_dashboard/notifications'
    | '/auth/$authView'
    | '/_dashboard/bookings/$bookingId'
    | '/_dashboard/settings/account'
    | '/_dashboard/settings/billing'
    | '/_dashboard/settings/schedule'
    | '/_dashboard/settings/security'
    | '/_dashboard/bookings/'
    | '/_dashboard/bookings/host/$personId'
    | '/_dashboard/bookings/host/$personId/$slotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bookings/': {
      id: '/_dashboard/bookings/'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof DashboardBookingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/security': {
      id: '/_dashboard/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/schedule': {
      id: '/_dashboard/settings/schedule'
      path: '/settings/schedule'
      fullPath: '/settings/schedule'
      preLoaderRoute: typeof DashboardSettingsScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/billing': {
      id: '/_dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/account': {
      id: '/_dashboard/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bookings/$bookingId': {
      id: '/_dashboard/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof DashboardBookingsBookingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bookings/host/$personId': {
      id: '/_dashboard/bookings/host/$personId'
      path: '/bookings/host/$personId'
      fullPath: '/bookings/host/$personId'
      preLoaderRoute: typeof DashboardBookingsHostPersonIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bookings/host/$personId/$slotId': {
      id: '/_dashboard/bookings/host/$personId/$slotId'
      path: '/$slotId'
      fullPath: '/bookings/host/$personId/$slotId'
      preLoaderRoute: typeof DashboardBookingsHostPersonIdSlotIdRouteImport
      parentRoute: typeof DashboardBookingsHostPersonIdRoute
    }
  }
}

interface DashboardBookingsHostPersonIdRouteChildren {
  DashboardBookingsHostPersonIdSlotIdRoute: typeof DashboardBookingsHostPersonIdSlotIdRoute
}

const DashboardBookingsHostPersonIdRouteChildren: DashboardBookingsHostPersonIdRouteChildren =
  {
    DashboardBookingsHostPersonIdSlotIdRoute:
      DashboardBookingsHostPersonIdSlotIdRoute,
  }

const DashboardBookingsHostPersonIdRouteWithChildren =
  DashboardBookingsHostPersonIdRoute._addFileChildren(
    DashboardBookingsHostPersonIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardBookingsBookingIdRoute: typeof DashboardBookingsBookingIdRoute
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsScheduleRoute: typeof DashboardSettingsScheduleRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardBookingsIndexRoute: typeof DashboardBookingsIndexRoute
  DashboardBookingsHostPersonIdRoute: typeof DashboardBookingsHostPersonIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardBookingsBookingIdRoute: DashboardBookingsBookingIdRoute,
  DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsScheduleRoute: DashboardSettingsScheduleRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardBookingsIndexRoute: DashboardBookingsIndexRoute,
  DashboardBookingsHostPersonIdRoute:
    DashboardBookingsHostPersonIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
