/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DuesRouteImport } from './routes/dues'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersMembershipIdSendRouteImport } from './routes/members/$membershipId/send'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DuesRoute = DuesRouteImport.update({
  id: '/dues',
  path: '/dues',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMembershipIdSendRoute = MembersMembershipIdSendRouteImport.update({
  id: '/members/$membershipId/send',
  path: '/members/$membershipId/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dues': typeof DuesRoute
  '/import': typeof ImportRoute
  '/sign-in': typeof SignInRoute
  '/members/$membershipId/send': typeof MembersMembershipIdSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dues': typeof DuesRoute
  '/import': typeof ImportRoute
  '/sign-in': typeof SignInRoute
  '/members/$membershipId/send': typeof MembersMembershipIdSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dues': typeof DuesRoute
  '/import': typeof ImportRoute
  '/sign-in': typeof SignInRoute
  '/members/$membershipId/send': typeof MembersMembershipIdSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dues'
    | '/import'
    | '/sign-in'
    | '/members/$membershipId/send'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dues' | '/import' | '/sign-in' | '/members/$membershipId/send'
  id:
    | '__root__'
    | '/'
    | '/dues'
    | '/import'
    | '/sign-in'
    | '/members/$membershipId/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuesRoute: typeof DuesRoute
  ImportRoute: typeof ImportRoute
  SignInRoute: typeof SignInRoute
  MembersMembershipIdSendRoute: typeof MembersMembershipIdSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dues': {
      id: '/dues'
      path: '/dues'
      fullPath: '/dues'
      preLoaderRoute: typeof DuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$membershipId/send': {
      id: '/members/$membershipId/send'
      path: '/members/$membershipId/send'
      fullPath: '/members/$membershipId/send'
      preLoaderRoute: typeof MembersMembershipIdSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuesRoute: DuesRoute,
  ImportRoute: ImportRoute,
  SignInRoute: SignInRoute,
  MembersMembershipIdSendRoute: MembersMembershipIdSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
